// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: area_tecnico.sql

package repository

import (
	"context"
)

const listarAreasTecnico = `-- name: ListarAreasTecnico :many
SELECT id, nome FROM area_tecnico
WHERE tenant_id = $1
`

type ListarAreasTecnicoRow struct {
	ID   int16
	Nome string
}

// O caminho inverso de ObterAreaTecnicoPorNome: id -> nome, para devolver
// `area` em GET /usuarios(/:id) -- a tela de edição precisa dela para não
// abrir o técnico com a área em branco. Lista inteira e não um :one por
// usuário: são as poucas áreas do tenant, e a listagem paginada de usuários
// faria uma ida ao banco por técnico.
func (q *Queries) ListarAreasTecnico(ctx context.Context, tenantID int64) ([]ListarAreasTecnicoRow, error) {
	rows, err := q.db.Query(ctx, listarAreasTecnico, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarAreasTecnicoRow
	for rows.Next() {
		var i ListarAreasTecnicoRow
		if err := rows.Scan(&i.ID, &i.Nome); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterAreaTecnicoPorNome = `-- name: ObterAreaTecnicoPorNome :one
SELECT id FROM area_tecnico
WHERE tenant_id = $1 AND nome = $2
`

type ObterAreaTecnicoPorNomeParams struct {
	TenantID int64
	Nome     string
}

// Usado no cadastro de técnico: o front manda o nome da área (AreaTecnico em
// front-end/src/tipos/tecnico.ts), o banco guarda o id em usuario.area_tecnico_id.
func (q *Queries) ObterAreaTecnicoPorNome(ctx context.Context, arg ObterAreaTecnicoPorNomeParams) (int16, error) {
	row := q.db.QueryRow(ctx, obterAreaTecnicoPorNome, arg.TenantID, arg.Nome)
	var id int16
	err := row.Scan(&id)
	return id, err
}
