// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: area_tecnico.sql

package repository

import (
	"context"
)

const obterAreaTecnicoPorNome = `-- name: ObterAreaTecnicoPorNome :one
SELECT id FROM area_tecnico
WHERE tenant_id = $1 AND nome = $2
`

type ObterAreaTecnicoPorNomeParams struct {
	TenantID int64
	Nome     string
}

// Usado no cadastro de técnico: o front manda o nome da área (AreaTecnico em
// front-end/src/tipos/tecnico.ts), o banco guarda o id em usuario.area_tecnico_id.
func (q *Queries) ObterAreaTecnicoPorNome(ctx context.Context, arg ObterAreaTecnicoPorNomeParams) (int16, error) {
	row := q.db.QueryRow(ctx, obterAreaTecnicoPorNome, arg.TenantID, arg.Nome)
	var id int16
	err := row.Scan(&id)
	return id, err
}
