// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: empresa.sql

package repository

import (
	"context"
)

const obterEmpresaPorSubdominio = `-- name: ObterEmpresaPorSubdominio :one
SELECT id, nome
FROM empresa
WHERE subdominio = $1
  AND ativa
`

type ObterEmpresaPorSubdominioRow struct {
	ID   int64
	Nome string
}

func (q *Queries) ObterEmpresaPorSubdominio(ctx context.Context, subdominio string) (ObterEmpresaPorSubdominioRow, error) {
	row := q.db.QueryRow(ctx, obterEmpresaPorSubdominio, subdominio)
	var i ObterEmpresaPorSubdominioRow
	err := row.Scan(&i.ID, &i.Nome)
	return i, err
}
