// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loja.sql

package repository

import (
	"context"
)

const atualizarLoja = `-- name: AtualizarLoja :one
UPDATE loja
SET nome = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, nome, ativa, criado_em
`

type AtualizarLojaParams struct {
	ID       int64
	TenantID int64
	Nome     string
}

func (q *Queries) AtualizarLoja(ctx context.Context, arg AtualizarLojaParams) (Loja, error) {
	row := q.db.QueryRow(ctx, atualizarLoja, arg.ID, arg.TenantID, arg.Nome)
	var i Loja
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Nome,
		&i.Ativa,
		&i.CriadoEm,
	)
	return i, err
}

const contarSetoresAtivosDaLoja = `-- name: ContarSetoresAtivosDaLoja :one
SELECT count(*) FROM setor
WHERE tenant_id = $1 AND loja_id = $2 AND ativo
`

type ContarSetoresAtivosDaLojaParams struct {
	TenantID int64
	LojaID   int64
}

// Loja não é desativada por baixo dos setores: o escopo de acesso aponta pro
// setor (usuario_escopo_setor), então setor ativo pendurado em loja inativa
// continua dando acesso a uma loja que sumiu das listagens. Quem chama decide
// se recusa ou se desativa os setores junto, mas precisa saber que existem.
func (q *Queries) ContarSetoresAtivosDaLoja(ctx context.Context, arg ContarSetoresAtivosDaLojaParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarSetoresAtivosDaLoja, arg.TenantID, arg.LojaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarLoja = `-- name: CriarLoja :one

INSERT INTO loja (tenant_id, nome)
VALUES ($1, $2)
RETURNING id, tenant_id, nome, ativa, criado_em
`

type CriarLojaParams struct {
	TenantID int64
	Nome     string
}

// Loja é a unidade/filial dentro do tenant. Exclusão é sempre soft delete
// (ativa = false) -- ver "Soft delete" em docs/modelagem-banco-dados.md:
// máquina, setor e todo o histórico de OS apontam pra loja, então apagar de
// verdade levaria o histórico junto.
//
// ⚠️ A coluna é `ativa` (feminino) na loja e `ativo` no setor/usuário.
// Nome é único por tenant (uq_loja_tenant_nome): duplicado volta 23505 e
// vira ErrDadoDuplicado no helper, sem switch em pgErr.Code no service.
func (q *Queries) CriarLoja(ctx context.Context, arg CriarLojaParams) (Loja, error) {
	row := q.db.QueryRow(ctx, criarLoja, arg.TenantID, arg.Nome)
	var i Loja
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Nome,
		&i.Ativa,
		&i.CriadoEm,
	)
	return i, err
}

const desativarLoja = `-- name: DesativarLoja :execrows
UPDATE loja
SET ativa = false
WHERE id = $1 AND tenant_id = $2
`

type DesativarLojaParams struct {
	ID       int64
	TenantID int64
}

// :execrows e não :exec -- sem a contagem de linhas, desativar um id que não
// existe (ou que é de outro tenant) responderia igual a desativar um de
// verdade. Já desativada conta 1: o UPDATE casa a linha do mesmo jeito.
func (q *Queries) DesativarLoja(ctx context.Context, arg DesativarLojaParams) (int64, error) {
	result, err := q.db.Exec(ctx, desativarLoja, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarLojas = `-- name: ListarLojas :many
SELECT id, tenant_id, nome, ativa, criado_em FROM loja
WHERE tenant_id = $1
  AND ativa
ORDER BY nome
`

// Sem paginação nem filtro de busca de propósito: /lojas devolve array simples
// e o front pagina/filtra no cliente (front-end/CLAUDE.md item 12). Só
// /usuarios e /solicitacoes/minhas paginam no servidor.
func (q *Queries) ListarLojas(ctx context.Context, tenantID int64) ([]Loja, error) {
	rows, err := q.db.Query(ctx, listarLojas, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loja
	for rows.Next() {
		var i Loja
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Nome,
			&i.Ativa,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterLojaParaEscrita = `-- name: ObterLojaParaEscrita :one
SELECT id, tenant_id, nome, ativa, criado_em FROM loja
WHERE id = $1 AND tenant_id = $2
FOR SHARE
`

type ObterLojaParaEscritaParams struct {
	ID       int64
	TenantID int64
}

// Igual a ObterLojaPorID, com FOR SHARE: usada dentro da transação que cria
// setor, para a loja não ser desativada entre o cheque de `ativa` e o INSERT.
// FOR SHARE e não FOR UPDATE porque ninguém aqui altera a loja -- só precisa
// impedir que ela mude enquanto o setor entra.
func (q *Queries) ObterLojaParaEscrita(ctx context.Context, arg ObterLojaParaEscritaParams) (Loja, error) {
	row := q.db.QueryRow(ctx, obterLojaParaEscrita, arg.ID, arg.TenantID)
	var i Loja
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Nome,
		&i.Ativa,
		&i.CriadoEm,
	)
	return i, err
}

const obterLojaPorID = `-- name: ObterLojaPorID :one
SELECT id, tenant_id, nome, ativa, criado_em FROM loja
WHERE id = $1 AND tenant_id = $2
`

type ObterLojaPorIDParams struct {
	ID       int64
	TenantID int64
}

// Sem filtro de `ativa`, igual a ObterUsuarioPorID: a tela de edição precisa
// ler o registro para preencher o formulário, e quem decide o que fazer com
// uma loja desativada é o service.
func (q *Queries) ObterLojaPorID(ctx context.Context, arg ObterLojaPorIDParams) (Loja, error) {
	row := q.db.QueryRow(ctx, obterLojaPorID, arg.ID, arg.TenantID)
	var i Loja
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Nome,
		&i.Ativa,
		&i.CriadoEm,
	)
	return i, err
}
