// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maquina.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarMaquina = `-- name: AtualizarMaquina :one
UPDATE maquina
SET setor_id = $3,
    criticidade = $4,
    numero_patrimonio = $5,
    numero_serie = $6,
    nome = $7,
    descricao = $8,
    marca = $9,
    modelo = $10
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, setor_id, numero_patrimonio, numero_serie, nome, descricao, marca, modelo, foto_chave, ativa, criado_em, criticidade
`

type AtualizarMaquinaParams struct {
	ID               int64
	TenantID         int64
	SetorID          int64
	Criticidade      NivelCriticidade
	NumeroPatrimonio string
	NumeroSerie      *string
	Nome             string
	Descricao        *string
	Marca            *string
	Modelo           *string
}

// setor_id entra no SET (diferente de AtualizarSetor, que ignora loja_id):
// mover uma máquina de setor não arrasta setor/loja de ninguém, só o próprio
// histórico dela, então mudar é uma operação válida, não um bug.
func (q *Queries) AtualizarMaquina(ctx context.Context, arg AtualizarMaquinaParams) (Maquina, error) {
	row := q.db.QueryRow(ctx, atualizarMaquina,
		arg.ID,
		arg.TenantID,
		arg.SetorID,
		arg.Criticidade,
		arg.NumeroPatrimonio,
		arg.NumeroSerie,
		arg.Nome,
		arg.Descricao,
		arg.Marca,
		arg.Modelo,
	)
	var i Maquina
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SetorID,
		&i.NumeroPatrimonio,
		&i.NumeroSerie,
		&i.Nome,
		&i.Descricao,
		&i.Marca,
		&i.Modelo,
		&i.FotoChave,
		&i.Ativa,
		&i.CriadoEm,
		&i.Criticidade,
	)
	return i, err
}

const criarMaquina = `-- name: CriarMaquina :one

INSERT INTO maquina (
    tenant_id, setor_id, criticidade, numero_patrimonio, numero_serie,
    nome, descricao, marca, modelo
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, setor_id, numero_patrimonio, numero_serie, nome, descricao, marca, modelo, foto_chave, ativa, criado_em, criticidade
`

type CriarMaquinaParams struct {
	TenantID         int64
	SetorID          int64
	Criticidade      NivelCriticidade
	NumeroPatrimonio string
	NumeroSerie      *string
	Nome             string
	Descricao        *string
	Marca            *string
	Modelo           *string
}

// Máquina pertence a um setor (maquina só referencia setor_id -- a loja vem
// por join, docs/modelagem-banco-dados.md). Exclusão é soft delete
// (ativa = false), mesmo motivo de loja/setor: preventiva e o histórico de OS
// apontam pra máquina.
//
// criticidade é o ENUM nivel_criticidade ('Baixa','Média','Alta', migration
// 000004) e viaja com o mesmo texto que o front manda -- sem resolução
// nome->id como em area_tecnico_id.
//
// foto_chave fica de fora do Criar/Atualizar de propósito: o upload
// (bucketR2.UploadFoto) ainda não está wireado em nenhuma rota (ver
// back-end/CLAUDE.md, "R2 -- storage de anexos"). Adicionar quando o CRUD
// de fato subir a foto na mesma requisição.
//
// ⚠️ As duas leituras (ObterMaquinaPorID, ListarMaquinas) trazem setor_nome,
// loja_id e loja_nome por JOIN: o tipo Maquina do front exige setorNome e
// lojaId, e maquina não guarda loja_id -- a loja só existe via setor. É o
// padrão "nome vem denormalizado do servidor" de front-end/CLAUDE.md item 6:
// a tela não monta o nome procurando numa lista à parte.
//
// Criar/Atualizar não conseguem fazer isso: RETURNING não enxerga tabela
// juntada. Quem escrever o service resolve relendo por ObterMaquinaPorID
// dentro da mesma transação -- é o único jeito de a resposta do POST/PUT ter
// a mesma forma da resposta do GET.
// fk_maquina_setor é composta (tenant_id, setor_id) -> setor (tenant_id, id):
// o banco já recusa sozinho um setor de outro tenant, sem checagem extra
// aqui.
func (q *Queries) CriarMaquina(ctx context.Context, arg CriarMaquinaParams) (Maquina, error) {
	row := q.db.QueryRow(ctx, criarMaquina,
		arg.TenantID,
		arg.SetorID,
		arg.Criticidade,
		arg.NumeroPatrimonio,
		arg.NumeroSerie,
		arg.Nome,
		arg.Descricao,
		arg.Marca,
		arg.Modelo,
	)
	var i Maquina
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SetorID,
		&i.NumeroPatrimonio,
		&i.NumeroSerie,
		&i.Nome,
		&i.Descricao,
		&i.Marca,
		&i.Modelo,
		&i.FotoChave,
		&i.Ativa,
		&i.CriadoEm,
		&i.Criticidade,
	)
	return i, err
}

const desativarMaquina = `-- name: DesativarMaquina :execrows
UPDATE maquina
SET ativa = false
WHERE id = $1 AND tenant_id = $2
`

type DesativarMaquinaParams struct {
	ID       int64
	TenantID int64
}

// :execrows e não :exec, mesmo motivo de DesativarLoja/DesativarSetor: sem a
// contagem de linhas, desativar um id que não existe (ou é de outro tenant)
// responderia sucesso igual a desativar um de verdade.
func (q *Queries) DesativarMaquina(ctx context.Context, arg DesativarMaquinaParams) (int64, error) {
	result, err := q.db.Exec(ctx, desativarMaquina, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarMaquinas = `-- name: ListarMaquinas :many
SELECT m.id, m.tenant_id, m.setor_id, m.numero_patrimonio, m.numero_serie, m.nome, m.descricao, m.marca, m.modelo, m.foto_chave, m.ativa, m.criado_em, m.criticidade, s.nome AS setor_nome, s.loja_id, l.nome AS loja_nome
FROM maquina m
JOIN setor s ON s.tenant_id = m.tenant_id AND s.id = m.setor_id
JOIN loja  l ON l.tenant_id = s.tenant_id AND l.id = s.loja_id
WHERE m.tenant_id = $1
  AND m.ativa
  AND ($2::bigint IS NULL OR m.setor_id = $2)
  AND ($3::bigint IS NULL OR s.loja_id = $3)
ORDER BY m.nome
`

type ListarMaquinasParams struct {
	TenantID int64
	SetorID  *int64
	LojaID   *int64
}

type ListarMaquinasRow struct {
	ID               int64
	TenantID         int64
	SetorID          int64
	NumeroPatrimonio string
	NumeroSerie      *string
	Nome             string
	Descricao        *string
	Marca            *string
	Modelo           *string
	FotoChave        *string
	Ativa            bool
	CriadoEm         pgtype.Timestamptz
	Criticidade      NivelCriticidade
	SetorNome        string
	LojaID           int64
	LojaNome         string
}

// setorId e lojaId são opcionais e combináveis (ParametrosListagemMaquinas no
// front) -- NULL não filtra, mesmo padrão de ListarSetores. O JOIN com setor
// é o que permite filtrar por loja, já que maquina não guarda loja_id.
//
// Filtra só por m.ativa, não por s.ativo/l.ativa: máquina em setor desativado
// continua listada. É o comportamento certo enquanto DesativarSetor não
// recusar (nem cascatear) com máquina ativa pendurada -- hoje não faz nem um
// nem outro, diferente de DesativarLoja, que recusa com setor ativo.
//
// Array simples, sem paginação: o front pagina no cliente.
func (q *Queries) ListarMaquinas(ctx context.Context, arg ListarMaquinasParams) ([]ListarMaquinasRow, error) {
	rows, err := q.db.Query(ctx, listarMaquinas, arg.TenantID, arg.SetorID, arg.LojaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarMaquinasRow
	for rows.Next() {
		var i ListarMaquinasRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SetorID,
			&i.NumeroPatrimonio,
			&i.NumeroSerie,
			&i.Nome,
			&i.Descricao,
			&i.Marca,
			&i.Modelo,
			&i.FotoChave,
			&i.Ativa,
			&i.CriadoEm,
			&i.Criticidade,
			&i.SetorNome,
			&i.LojaID,
			&i.LojaNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterMaquinaPorID = `-- name: ObterMaquinaPorID :one
SELECT m.id, m.tenant_id, m.setor_id, m.numero_patrimonio, m.numero_serie, m.nome, m.descricao, m.marca, m.modelo, m.foto_chave, m.ativa, m.criado_em, m.criticidade, s.nome AS setor_nome, s.loja_id, l.nome AS loja_nome
FROM maquina m
JOIN setor s ON s.tenant_id = m.tenant_id AND s.id = m.setor_id
JOIN loja  l ON l.tenant_id = s.tenant_id AND l.id = s.loja_id
WHERE m.id = $1 AND m.tenant_id = $2
`

type ObterMaquinaPorIDParams struct {
	ID       int64
	TenantID int64
}

type ObterMaquinaPorIDRow struct {
	ID               int64
	TenantID         int64
	SetorID          int64
	NumeroPatrimonio string
	NumeroSerie      *string
	Nome             string
	Descricao        *string
	Marca            *string
	Modelo           *string
	FotoChave        *string
	Ativa            bool
	CriadoEm         pgtype.Timestamptz
	Criticidade      NivelCriticidade
	SetorNome        string
	LojaID           int64
	LojaNome         string
}

// Sem filtro de `ativa`, igual a ObterLojaPorID/ObterUsuarioPorID: a tela de
// edição precisa ler o registro para preencher o formulário mesmo desativado.
//
// Os JOINs são INNER e não LEFT de propósito: setor_id e setor.loja_id são
// NOT NULL com FK, então não existe máquina sem setor nem setor sem loja --
// LEFT só faria o Go receber ponteiro em campo que nunca é nulo.
func (q *Queries) ObterMaquinaPorID(ctx context.Context, arg ObterMaquinaPorIDParams) (ObterMaquinaPorIDRow, error) {
	row := q.db.QueryRow(ctx, obterMaquinaPorID, arg.ID, arg.TenantID)
	var i ObterMaquinaPorIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SetorID,
		&i.NumeroPatrimonio,
		&i.NumeroSerie,
		&i.Nome,
		&i.Descricao,
		&i.Marca,
		&i.Modelo,
		&i.FotoChave,
		&i.Ativa,
		&i.CriadoEm,
		&i.Criticidade,
		&i.SetorNome,
		&i.LojaID,
		&i.LojaNome,
	)
	return i, err
}
