// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maquina.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarMaquina = `-- name: AtualizarMaquina :one
UPDATE maquina
SET setor_id = $3,
    criticidade = $4,
    numero_patrimonio = $5,
    numero_serie = $6,
    nome = $7,
    descricao = $8,
    marca = $9,
    modelo = $10,
    foto_chave = COALESCE($11, foto_chave)
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, setor_id, numero_patrimonio, numero_serie, nome, descricao, marca, modelo, foto_chave, ativa, criado_em, criticidade
`

type AtualizarMaquinaParams struct {
	ID               int64
	TenantID         int64
	SetorID          int64
	Criticidade      NivelCriticidade
	NumeroPatrimonio string
	NumeroSerie      *string
	Nome             string
	Descricao        *string
	Marca            *string
	Modelo           *string
	FotoChave        *string
}

// setor_id entra no SET (diferente de AtualizarSetor, que ignora loja_id):
// mover uma máquina de setor não arrasta setor/loja de ninguém, só o próprio
// histórico dela, então mudar é uma operação válida, não um bug.
func (q *Queries) AtualizarMaquina(ctx context.Context, arg AtualizarMaquinaParams) (Maquina, error) {
	row := q.db.QueryRow(ctx, atualizarMaquina,
		arg.ID,
		arg.TenantID,
		arg.SetorID,
		arg.Criticidade,
		arg.NumeroPatrimonio,
		arg.NumeroSerie,
		arg.Nome,
		arg.Descricao,
		arg.Marca,
		arg.Modelo,
		arg.FotoChave,
	)
	var i Maquina
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SetorID,
		&i.NumeroPatrimonio,
		&i.NumeroSerie,
		&i.Nome,
		&i.Descricao,
		&i.Marca,
		&i.Modelo,
		&i.FotoChave,
		&i.Ativa,
		&i.CriadoEm,
		&i.Criticidade,
	)
	return i, err
}

const criarMaquina = `-- name: CriarMaquina :one

INSERT INTO maquina (
    tenant_id, setor_id, criticidade, numero_patrimonio, numero_serie,
    nome, descricao, marca, modelo, foto_chave
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, setor_id, numero_patrimonio, numero_serie, nome, descricao, marca, modelo, foto_chave, ativa, criado_em, criticidade
`

type CriarMaquinaParams struct {
	TenantID         int64
	SetorID          int64
	Criticidade      NivelCriticidade
	NumeroPatrimonio string
	NumeroSerie      *string
	Nome             string
	Descricao        *string
	Marca            *string
	Modelo           *string
	FotoChave        *string
}

// Máquina pertence a um setor (maquina só referencia setor_id -- a loja vem
// por join, docs/modelagem-banco-dados.md). Exclusão é soft delete
// (ativa = false), mesmo motivo de loja/setor: preventiva e o histórico de OS
// apontam pra máquina.
//
// criticidade é o ENUM nivel_criticidade ('Baixa','Média','Alta', migration
// 000004) e viaja com o mesmo texto que o front manda -- sem resolução
// nome->id como em area_tecnico_id.
//
// foto_chave é a KEY do objeto no R2, nunca uma URL: a leitura é assinada na
// hora (bucketR2.URLLeitura, ver back-end/CLAUDE.md "R2 -- storage de
// anexos"). Entra em CriarMaquina porque o POST /maquinas sobe a foto na
// mesma requisição; NULL quando o cliente não mandou nenhuma.
//
// Em AtualizarMaquina ela entra como COALESCE($11, foto_chave): sem foto nova
// no multipart o valor chega NULL e a antiga fica. É o que a tela de edição
// precisa -- o front só sabe *trocar* a foto, não remover (UploadFoto em
// CadastrarMaquina.tsx), então NULL ali significa "não mexi", não "apague".
// ⚠️ Trocar a foto deixa o objeto antigo órfão no bucket: ninguém apaga do R2.
// É lixo barato e sem referência; se incomodar, o caminho é um DELETE do
// objeto antigo depois do commit (nunca antes -- a transação pode voltar).
//
// ⚠️ As duas leituras (ObterMaquinaPorID, ListarMaquinas) trazem setor_nome,
// loja_id e loja_nome por JOIN: o tipo Maquina do front exige setorNome e
// lojaId, e maquina não guarda loja_id -- a loja só existe via setor. É o
// padrão "nome vem denormalizado do servidor" de front-end/CLAUDE.md item 6:
// a tela não monta o nome procurando numa lista à parte.
//
// Criar/Atualizar não conseguem fazer isso: RETURNING não enxerga tabela
// juntada. Quem escrever o service resolve relendo por ObterMaquinaPorID
// dentro da mesma transação -- é o único jeito de a resposta do POST/PUT ter
// a mesma forma da resposta do GET.
// fk_maquina_setor é composta (tenant_id, setor_id) -> setor (tenant_id, id):
// o banco já recusa sozinho um setor de outro tenant, sem checagem extra
// aqui.
func (q *Queries) CriarMaquina(ctx context.Context, arg CriarMaquinaParams) (Maquina, error) {
	row := q.db.QueryRow(ctx, criarMaquina,
		arg.TenantID,
		arg.SetorID,
		arg.Criticidade,
		arg.NumeroPatrimonio,
		arg.NumeroSerie,
		arg.Nome,
		arg.Descricao,
		arg.Marca,
		arg.Modelo,
		arg.FotoChave,
	)
	var i Maquina
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SetorID,
		&i.NumeroPatrimonio,
		&i.NumeroSerie,
		&i.Nome,
		&i.Descricao,
		&i.Marca,
		&i.Modelo,
		&i.FotoChave,
		&i.Ativa,
		&i.CriadoEm,
		&i.Criticidade,
	)
	return i, err
}

const desativarMaquina = `-- name: DesativarMaquina :execrows
UPDATE maquina
SET ativa = false
WHERE id = $1 AND tenant_id = $2
`

type DesativarMaquinaParams struct {
	ID       int64
	TenantID int64
}

// :execrows e não :exec, mesmo motivo de DesativarLoja/DesativarSetor: sem a
// contagem de linhas, desativar um id que não existe (ou é de outro tenant)
// responderia sucesso igual a desativar um de verdade.
func (q *Queries) DesativarMaquina(ctx context.Context, arg DesativarMaquinaParams) (int64, error) {
	result, err := q.db.Exec(ctx, desativarMaquina, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarMaquinas = `-- name: ListarMaquinas :many
SELECT m.id, m.tenant_id, m.setor_id, m.numero_patrimonio, m.numero_serie, m.nome, m.descricao, m.marca, m.modelo, m.foto_chave, m.ativa, m.criado_em, m.criticidade, s.nome AS setor_nome, s.loja_id, l.nome AS loja_nome
FROM maquina m
JOIN setor s ON s.tenant_id = m.tenant_id AND s.id = m.setor_id
JOIN loja  l ON l.tenant_id = s.tenant_id AND l.id = s.loja_id
WHERE m.tenant_id = $1
  AND m.ativa
  AND ($2::bigint IS NULL OR m.setor_id = $2)
  AND ($3::bigint IS NULL OR s.loja_id = $3)
  -- Escopo de acesso no WHERE, nunca no cliente (back-end/CLAUDE.md, "Regras
  -- herdadas do contrato com o front"): NULL não filtra e é o caso do
  -- administrador, que não tem escopo nenhum -- a ausência dele É o acesso
  -- total ao tenant. Para os outros perfis o service manda o usuario.id do
  -- token e a linha só aparece se ele alcança a loja E o setor:
  --   solicitante -> um escopo, um setor;
  --   tecnico     -> escopos com acesso_total_setores (escopoDoPerfil);
  --   gestor      -> setores marcados, ou a loja inteira quando total.
  -- EXISTS e não JOIN, mesmo motivo de ListarUsuarios: com JOIN a máquina
  -- apareceria uma vez por escopo que a alcança.
  AND (
    $4::bigint IS NULL
    OR EXISTS (
      SELECT 1
      FROM usuario_escopo ue
      LEFT JOIN usuario_escopo_setor ues ON ues.escopo_id = ue.id
      WHERE ue.usuario_id = $4
        AND ue.loja_id = s.loja_id
        AND (ue.acesso_total_setores OR ues.setor_id = m.setor_id)
    )
  )
ORDER BY m.nome
`

type ListarMaquinasParams struct {
	TenantID        int64
	SetorID         *int64
	LojaID          *int64
	EscopoUsuarioID *int64
}

type ListarMaquinasRow struct {
	ID               int64
	TenantID         int64
	SetorID          int64
	NumeroPatrimonio string
	NumeroSerie      *string
	Nome             string
	Descricao        *string
	Marca            *string
	Modelo           *string
	FotoChave        *string
	Ativa            bool
	CriadoEm         pgtype.Timestamptz
	Criticidade      NivelCriticidade
	SetorNome        string
	LojaID           int64
	LojaNome         string
}

// setorId e lojaId são opcionais e combináveis (ParametrosListagemMaquinas no
// front) -- NULL não filtra, mesmo padrão de ListarSetores. O JOIN com setor
// é o que permite filtrar por loja, já que maquina não guarda loja_id.
//
// Filtra só por m.ativa, não por s.ativo/l.ativa: máquina em setor desativado
// continua listada. É o comportamento certo enquanto DesativarSetor não
// recusar (nem cascatear) com máquina ativa pendurada -- hoje não faz nem um
// nem outro, diferente de DesativarLoja, que recusa com setor ativo.
//
// Array simples, sem paginação: o front pagina no cliente.
func (q *Queries) ListarMaquinas(ctx context.Context, arg ListarMaquinasParams) ([]ListarMaquinasRow, error) {
	rows, err := q.db.Query(ctx, listarMaquinas,
		arg.TenantID,
		arg.SetorID,
		arg.LojaID,
		arg.EscopoUsuarioID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarMaquinasRow
	for rows.Next() {
		var i ListarMaquinasRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SetorID,
			&i.NumeroPatrimonio,
			&i.NumeroSerie,
			&i.Nome,
			&i.Descricao,
			&i.Marca,
			&i.Modelo,
			&i.FotoChave,
			&i.Ativa,
			&i.CriadoEm,
			&i.Criticidade,
			&i.SetorNome,
			&i.LojaID,
			&i.LojaNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterMaquinaPorID = `-- name: ObterMaquinaPorID :one
SELECT m.id, m.tenant_id, m.setor_id, m.numero_patrimonio, m.numero_serie, m.nome, m.descricao, m.marca, m.modelo, m.foto_chave, m.ativa, m.criado_em, m.criticidade, s.nome AS setor_nome, s.loja_id, l.nome AS loja_nome
FROM maquina m
JOIN setor s ON s.tenant_id = m.tenant_id AND s.id = m.setor_id
JOIN loja  l ON l.tenant_id = s.tenant_id AND l.id = s.loja_id
WHERE m.id = $1 AND m.tenant_id = $2
  AND (
    $3::bigint IS NULL
    OR EXISTS (
      SELECT 1
      FROM usuario_escopo ue
      LEFT JOIN usuario_escopo_setor ues ON ues.escopo_id = ue.id
      WHERE ue.usuario_id = $3
        AND ue.loja_id = s.loja_id
        AND (ue.acesso_total_setores OR ues.setor_id = m.setor_id)
    )
  )
`

type ObterMaquinaPorIDParams struct {
	ID              int64
	TenantID        int64
	EscopoUsuarioID *int64
}

type ObterMaquinaPorIDRow struct {
	ID               int64
	TenantID         int64
	SetorID          int64
	NumeroPatrimonio string
	NumeroSerie      *string
	Nome             string
	Descricao        *string
	Marca            *string
	Modelo           *string
	FotoChave        *string
	Ativa            bool
	CriadoEm         pgtype.Timestamptz
	Criticidade      NivelCriticidade
	SetorNome        string
	LojaID           int64
	LojaNome         string
}

// Sem filtro de `ativa`, igual a ObterLojaPorID/ObterUsuarioPorID: a tela de
// edição precisa ler o registro para preencher o formulário mesmo desativado.
//
// Os JOINs são INNER e não LEFT de propósito: setor_id e setor.loja_id são
// NOT NULL com FK, então não existe máquina sem setor nem setor sem loja --
// LEFT só faria o Go receber ponteiro em campo que nunca é nulo.
//
// O escopo é OPCIONAL aqui, diferente de ListarMaquinas: NULL não filtra, e é
// o que os chamadores de escrita mandam (CadastrarMaquina/AtualizarMaquina
// releem a linha que acabaram de gravar, o job de preventiva não tem sessão) e
// também o administrador, que não tem escopo. Quem passa o usuário é
// GET /indicadores/maquinas/:id, aberto ao Gestor: sem o EXISTS ele leria
// custo e indisponibilidade de máquina de outra loja enumerando id -- mesma
// lacuna que ObterSolicitacaoPorID fechou na fase 1.
func (q *Queries) ObterMaquinaPorID(ctx context.Context, arg ObterMaquinaPorIDParams) (ObterMaquinaPorIDRow, error) {
	row := q.db.QueryRow(ctx, obterMaquinaPorID, arg.ID, arg.TenantID, arg.EscopoUsuarioID)
	var i ObterMaquinaPorIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SetorID,
		&i.NumeroPatrimonio,
		&i.NumeroSerie,
		&i.Nome,
		&i.Descricao,
		&i.Marca,
		&i.Modelo,
		&i.FotoChave,
		&i.Ativa,
		&i.CriadoEm,
		&i.Criticidade,
		&i.SetorNome,
		&i.LojaID,
		&i.LojaNome,
	)
	return i, err
}
