// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preventiva.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarPreventiva = `-- name: AtualizarPreventiva :one
UPDATE preventiva
SET descricao = $3,
    intervalo_dias = $4,
    proxima_data = $5,
    ativa = $6,
    tecnico_id = $7::bigint
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, maquina_id, descricao, intervalo_dias, proxima_data, ativa, criado_em, tecnico_id
`

type AtualizarPreventivaParams struct {
	ID            int64
	TenantID      int64
	Descricao     string
	IntervaloDias int32
	ProximaData   pgtype.Date
	Ativa         bool
	TecnicoID     *int64
}

// Sem maquina_id, mesmo motivo de AtualizarSetor não mexer em loja_id: mover a
// preventiva de máquina deixaria as solicitações que ela já gerou apontando
// para uma máquina que não é mais a dela. O front manda o campo no PUT; o
// service ignora.
//
// tecnico_id ENTRA aqui, diferente de maquina_id: trocar quem atende a
// preventiva é justamente o que a edição serve para fazer (técnico saiu da
// empresa, mudou de área), e não desfaz nada -- as OS já abertas guardam o
// técnico delas em ordem_servico.tecnico_id, não olham mais para cá.
func (q *Queries) AtualizarPreventiva(ctx context.Context, arg AtualizarPreventivaParams) (Preventiva, error) {
	row := q.db.QueryRow(ctx, atualizarPreventiva,
		arg.ID,
		arg.TenantID,
		arg.Descricao,
		arg.IntervaloDias,
		arg.ProximaData,
		arg.Ativa,
		arg.TecnicoID,
	)
	var i Preventiva
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MaquinaID,
		&i.Descricao,
		&i.IntervaloDias,
		&i.ProximaData,
		&i.Ativa,
		&i.CriadoEm,
		&i.TecnicoID,
	)
	return i, err
}

const avancarProximaData = `-- name: AvancarProximaData :one
UPDATE preventiva
SET proxima_data = proxima_data + (intervalo_dias * INTERVAL '1 day')
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, maquina_id, descricao, intervalo_dias, proxima_data, ativa, criado_em, tecnico_id
`

type AvancarProximaDataParams struct {
	ID       int64
	TenantID int64
}

// Roda quando a preventiva vence e gera a solicitação automática: empurra a
// próxima data em intervalo_dias a partir da data vencida (não a partir de
// hoje) -- senão um ciclo processado com atraso arrastaria todos os seguintes.
func (q *Queries) AvancarProximaData(ctx context.Context, arg AvancarProximaDataParams) (Preventiva, error) {
	row := q.db.QueryRow(ctx, avancarProximaData, arg.ID, arg.TenantID)
	var i Preventiva
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MaquinaID,
		&i.Descricao,
		&i.IntervaloDias,
		&i.ProximaData,
		&i.Ativa,
		&i.CriadoEm,
		&i.TecnicoID,
	)
	return i, err
}

const criarPreventiva = `-- name: CriarPreventiva :one

INSERT INTO preventiva (tenant_id, maquina_id, descricao, intervalo_dias, proxima_data, ativa, tecnico_id)
VALUES ($1, $2, $3, $4, $5, $6, $7::bigint)
RETURNING id, tenant_id, maquina_id, descricao, intervalo_dias, proxima_data, ativa, criado_em, tecnico_id
`

type CriarPreventivaParams struct {
	TenantID      int64
	MaquinaID     int64
	Descricao     string
	IntervaloDias int32
	ProximaData   pgtype.Date
	Ativa         bool
	TecnicoID     *int64
}

// Manutenção preventiva de uma máquina. Máquina exige pelo menos uma
// (regra de negócio do front: esquemaCadastrarMaquina, preventivas min(1)), e
// elas viajam na mesma requisição da máquina -- CriarPreventiva é chamada
// tanto por POST /preventivas quanto por CadastrarMaquina, dentro da mesma
// transação.
//
// Exclusão é soft delete (ativa = false), e aqui isso não é só convenção da
// casa: fk_solicitacao_preventiva não tem ON DELETE, então toda preventiva que
// já disparou uma solicitação automática (origem = 'preventiva') recusaria o
// DELETE com 23503. Soft delete é o único caminho que não quebra depois do
// primeiro ciclo vencer.
//
// ⚠️ `ativa` acumula dois sentidos: o alternador "Preventiva habilitada no
// sistema" do ModalManutencaoPreventiva e o soft delete do DELETE
// /preventivas/:id. Desabilitar pelo modal e excluir produzem o mesmo estado --
// em ambos a preventiva para de vencer e some da listagem. Consistente com o
// resto do sistema (não existe reativação pela API), mas é uma decisão, não um
// acidente.
//
// proxima_data é `date`, não timestamptz: preventiva vence no dia, não na hora
// (docs/modelagem-banco-dados.md, seção 3).
// fk_preventiva_maquina é composta (tenant_id, maquina_id): o banco recusa
// sozinho pendurar preventiva em máquina de outro tenant.
// ck_intervalo (intervalo_dias > 0) volta 23514 e vira ErrConflitoIntegridade.
//
// tecnico_id é quem vai receber a OS quando esta preventiva vencer (migration
// 000008): o job não escolhe técnico, lê o que está aqui. A coluna é nullable
// no schema para a migration não falhar com dado dentro, mas o service exige
// o campo -- preventiva sem técnico não tem para quem abrir OS.
func (q *Queries) CriarPreventiva(ctx context.Context, arg CriarPreventivaParams) (Preventiva, error) {
	row := q.db.QueryRow(ctx, criarPreventiva,
		arg.TenantID,
		arg.MaquinaID,
		arg.Descricao,
		arg.IntervaloDias,
		arg.ProximaData,
		arg.Ativa,
		arg.TecnicoID,
	)
	var i Preventiva
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MaquinaID,
		&i.Descricao,
		&i.IntervaloDias,
		&i.ProximaData,
		&i.Ativa,
		&i.CriadoEm,
		&i.TecnicoID,
	)
	return i, err
}

const desativarPreventiva = `-- name: DesativarPreventiva :execrows
UPDATE preventiva
SET ativa = false
WHERE id = $1 AND tenant_id = $2
`

type DesativarPreventivaParams struct {
	ID       int64
	TenantID int64
}

// :execrows e não :exec, mesmo motivo de DesativarLoja/DesativarSetor: sem a
// contagem de linhas, desativar um id inexistente (ou de outro tenant)
// responderia sucesso igual a desativar um de verdade.
func (q *Queries) DesativarPreventiva(ctx context.Context, arg DesativarPreventivaParams) (int64, error) {
	result, err := q.db.Exec(ctx, desativarPreventiva, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const desativarPreventivasDaMaquina = `-- name: DesativarPreventivasDaMaquina :exec
UPDATE preventiva
SET ativa = false
WHERE tenant_id = $1 AND maquina_id = $2
`

type DesativarPreventivasDaMaquinaParams struct {
	TenantID  int64
	MaquinaID int64
}

// PUT /maquinas/:id substitui o conjunto inteiro de preventivas (não faz merge
// incremental): o service desativa todas as da máquina e insere as novas, na
// mesma transação -- mesmo padrão do escopo de acesso em AtualizarUsuario.
//
// Desativa em vez de deletar justamente por causa de fk_solicitacao_preventiva:
// um DELETE aqui quebraria a edição de qualquer máquina cuja preventiva já
// tivesse vencido uma vez.
func (q *Queries) DesativarPreventivasDaMaquina(ctx context.Context, arg DesativarPreventivasDaMaquinaParams) error {
	_, err := q.db.Exec(ctx, desativarPreventivasDaMaquina, arg.TenantID, arg.MaquinaID)
	return err
}

const listarPreventivas = `-- name: ListarPreventivas :many
SELECT
    p.id, p.tenant_id, p.maquina_id, p.descricao, p.intervalo_dias, p.proxima_data, p.ativa, p.criado_em, p.tecnico_id,
    m.nome AS maquina_nome,
    m.setor_id,
    s.nome AS setor_nome,
    s.loja_id,
    l.nome AS loja_nome,
    t.nome AS tecnico_nome,
    COALESCE(p.ativa AND p.proxima_data <= (now() AT TIME ZONE 'America/Sao_Paulo')::date, false)::boolean AS vencida
FROM preventiva p
JOIN maquina m ON m.tenant_id = p.tenant_id AND m.id = p.maquina_id
JOIN setor   s ON s.tenant_id = m.tenant_id AND s.id = m.setor_id
JOIN loja    l ON l.tenant_id = s.tenant_id AND l.id = s.loja_id
LEFT JOIN usuario t ON t.tenant_id = p.tenant_id AND t.id = p.tecnico_id
WHERE p.tenant_id = $1
  AND p.ativa
  AND ($2::bigint IS NULL OR p.maquina_id = $2)
  -- Escopo de acesso no WHERE, nunca no cliente (back-end/CLAUDE.md, "Regras
  -- herdadas do contrato com o front"): NULL não filtra e é o caso do
  -- administrador, que não tem escopo nenhum -- a ausência dele É o acesso
  -- total ao tenant. Para os outros perfis o service manda o usuario.id do
  -- token e a linha só aparece se ele alcança a loja E o setor:
  --   solicitante -> um escopo, um setor;
  --   tecnico     -> escopos com acesso_total_setores (escopoDoPerfil);
  --   gestor      -> setores marcados, ou a loja inteira quando total.
  -- EXISTS e não JOIN, mesmo motivo de ListarUsuarios: com JOIN a máquina
  -- apareceria uma vez por escopo que a alcança.
  AND (
    $3::bigint IS NULL
    OR EXISTS (
      SELECT 1
      FROM usuario_escopo ue
      LEFT JOIN usuario_escopo_setor ues ON ues.escopo_id = ue.id
      WHERE ue.usuario_id = $3
        AND ue.loja_id = s.loja_id
        AND (ue.acesso_total_setores OR ues.setor_id = m.setor_id)
    )
  )
ORDER BY p.proxima_data, p.id
`

type ListarPreventivasParams struct {
	TenantID        int64
	MaquinaID       *int64
	EscopoUsuarioID *int64
}

type ListarPreventivasRow struct {
	ID            int64
	TenantID      int64
	MaquinaID     int64
	Descricao     string
	IntervaloDias int32
	ProximaData   pgtype.Date
	Ativa         bool
	CriadoEm      pgtype.Timestamptz
	TecnicoID     *int64
	MaquinaNome   string
	SetorID       int64
	SetorNome     string
	LojaID        int64
	LojaNome      string
	TecnicoNome   *string
	Vencida       bool
}

// maquina_id é opcional (NULL não filtra): a aba "Manutenção Prev." do painel
// do gestor lista tudo, e a tela de edição de máquina pede só as dela
// (GET /preventivas?maquinaId=).
//
// `vencida` é calculado, nunca coluna -- o front só reage ao flag
// (front-end/CLAUDE.md, ModalManutencaoPreventiva). A data de corte usa o fuso
// de São Paulo explícito e não CURRENT_DATE: o container roda em UTC, e com
// CURRENT_DATE uma preventiva apareceria vencida até 3h antes da virada do dia
// no Brasil.
//
// Ordena por proxima_data: o que interessa na fila é o que vence antes, não a
// ordem alfabética da máquina. Array simples, sem paginação -- o front pagina
// no cliente.
// LEFT e não INNER: tecnico_id é nullable (preventiva anterior à migration
// 000008 não tem técnico). Com INNER essas linhas sumiriam da listagem, que é
// exatamente onde o Administrador precisa vê-las para corrigir.
func (q *Queries) ListarPreventivas(ctx context.Context, arg ListarPreventivasParams) ([]ListarPreventivasRow, error) {
	rows, err := q.db.Query(ctx, listarPreventivas, arg.TenantID, arg.MaquinaID, arg.EscopoUsuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPreventivasRow
	for rows.Next() {
		var i ListarPreventivasRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MaquinaID,
			&i.Descricao,
			&i.IntervaloDias,
			&i.ProximaData,
			&i.Ativa,
			&i.CriadoEm,
			&i.TecnicoID,
			&i.MaquinaNome,
			&i.SetorID,
			&i.SetorNome,
			&i.LojaID,
			&i.LojaNome,
			&i.TecnicoNome,
			&i.Vencida,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPreventivasVencidas = `-- name: ListarPreventivasVencidas :many
SELECT
    p.id,
    p.tenant_id
FROM preventiva p
JOIN maquina m ON m.tenant_id = p.tenant_id AND m.id = p.maquina_id
WHERE p.ativa
  AND m.ativa
  AND p.proxima_data <= (now() AT TIME ZONE 'America/Sao_Paulo')::date
ORDER BY p.proxima_data, p.id
`

type ListarPreventivasVencidasRow struct {
	ID       int64
	TenantID int64
}

// Alimenta o job de abertura automática de solicitação (subcomando de CLI
// `preventivas-vencidas`, chamado pelo Railway Cron -- ver "Abertura automática
// de solicitação por preventiva" no CLAUDE.md). Cada linha daqui vira uma
// solicitação com origem = 'preventiva' e a OS dela, já atribuída ao técnico
// da própria preventiva -- desde a migration 000008 isto não passa pela fila
// do Gestor.
//
// ⚠️ É a única query do projeto SEM tenant_id no WHERE, e isso é proposital:
// não há request, não há token, não há tenant. O job varre todos os tenants de
// uma vez e o tenant_id viaja na linha, direto para o INSERT da solicitação.
// Não "conserte" isso adicionando um filtro.
//
// Sem parâmetro nenhum, pelo mesmo motivo.
//
// ⚠️ O NOT EXISTS sobre solicitação 'Pendente' que morava aqui SAIU, junto com
// uq_preventiva_pendente (migration 000008), e os dois pelo mesmo motivo: a
// solicitação de preventiva não passa mais pela fila do Gestor, nasce
// 'Convertida' com a OS junto. O filtro existia para pular a preventiva que
// estava parada esperando aprovação -- estado que deixou de existir, porque
// AvancarProximaData roda na mesma transação e joga a data para o próximo
// ciclo. Não devolva o filtro: ele nunca casaria e esconderia essa mudança.
//
// Quem protege contra duas réplicas do cron abrindo o mesmo ciclo duas vezes
// agora é ObterPreventivaVencidaParaAbertura (SELECT ... FOR UPDATE) na
// transação de cada preventiva -- esta query aqui é só a varredura, e ler uma
// linha que outra réplica já processou é esperado.
//
// m.ativa é igualmente obrigatório: DesativarMaquina NÃO desativa as
// preventivas da máquina (maquina.sql, e não há ON DELETE/trigger fazendo
// isso). Sem esse filtro, máquina desativada continuaria abrindo solicitação a
// cada ciclo, para sempre, e não haveria como parar pela API -- não existe
// reativação nem DELETE de linha em lugar nenhum.
//
// A data de corte usa fuso explícito e não CURRENT_DATE, mesmo motivo do
// `vencida` nas outras duas queries: o container roda em UTC, e a preventiva
// apareceria vencida até 3h antes da virada do dia no Brasil.
//
// Projeta só id e tenant_id: o resto (descrição, máquina, setor, técnico) é
// relido sob lock por ObterPreventivaVencidaParaAbertura, dentro da transação
// de cada preventiva. Carregar os campos aqui seria carregar um retrato que
// pode estar velho quando o INSERT acontecer. Não usa p.* como as outras:
// aqui ninguém monta resposta de contrato.
func (q *Queries) ListarPreventivasVencidas(ctx context.Context) ([]ListarPreventivasVencidasRow, error) {
	rows, err := q.db.Query(ctx, listarPreventivasVencidas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPreventivasVencidasRow
	for rows.Next() {
		var i ListarPreventivasVencidasRow
		if err := rows.Scan(&i.ID, &i.TenantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterPreventivaPorID = `-- name: ObterPreventivaPorID :one
SELECT
    p.id, p.tenant_id, p.maquina_id, p.descricao, p.intervalo_dias, p.proxima_data, p.ativa, p.criado_em, p.tecnico_id,
    m.nome AS maquina_nome,
    m.setor_id,
    s.nome AS setor_nome,
    s.loja_id,
    l.nome AS loja_nome,
    t.nome AS tecnico_nome,
    COALESCE(p.ativa AND p.proxima_data <= (now() AT TIME ZONE 'America/Sao_Paulo')::date, false)::boolean AS vencida
FROM preventiva p
JOIN maquina m ON m.tenant_id = p.tenant_id AND m.id = p.maquina_id
JOIN setor   s ON s.tenant_id = m.tenant_id AND s.id = m.setor_id
JOIN loja    l ON l.tenant_id = s.tenant_id AND l.id = s.loja_id
LEFT JOIN usuario t ON t.tenant_id = p.tenant_id AND t.id = p.tecnico_id
WHERE p.id = $1 AND p.tenant_id = $2
`

type ObterPreventivaPorIDParams struct {
	ID       int64
	TenantID int64
}

type ObterPreventivaPorIDRow struct {
	ID            int64
	TenantID      int64
	MaquinaID     int64
	Descricao     string
	IntervaloDias int32
	ProximaData   pgtype.Date
	Ativa         bool
	CriadoEm      pgtype.Timestamptz
	TecnicoID     *int64
	MaquinaNome   string
	SetorID       int64
	SetorNome     string
	LojaID        int64
	LojaNome      string
	TecnicoNome   *string
	Vencida       bool
}

// Traz os denormalizados porque PreventivaListada (o retorno de POST e PUT
// /preventivas, não só do GET) exige maquinaNome/setorId/setorNome/lojaId/
// lojaNome. RETURNING não enxerga tabela juntada, então Criar/Atualizar releem
// por aqui dentro da mesma transação para responder na forma do contrato.
//
// Sem filtro de `ativa`: a tela de edição precisa carregar o registro.
// LEFT e não INNER: tecnico_id é nullable (preventiva anterior à migration
// 000008 não tem técnico). Com INNER essas linhas sumiriam da listagem, que é
// exatamente onde o Administrador precisa vê-las para corrigir.
func (q *Queries) ObterPreventivaPorID(ctx context.Context, arg ObterPreventivaPorIDParams) (ObterPreventivaPorIDRow, error) {
	row := q.db.QueryRow(ctx, obterPreventivaPorID, arg.ID, arg.TenantID)
	var i ObterPreventivaPorIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MaquinaID,
		&i.Descricao,
		&i.IntervaloDias,
		&i.ProximaData,
		&i.Ativa,
		&i.CriadoEm,
		&i.TecnicoID,
		&i.MaquinaNome,
		&i.SetorID,
		&i.SetorNome,
		&i.LojaID,
		&i.LojaNome,
		&i.TecnicoNome,
		&i.Vencida,
	)
	return i, err
}

const obterPreventivaVencidaParaAbertura = `-- name: ObterPreventivaVencidaParaAbertura :one
SELECT
    p.id,
    p.tenant_id,
    p.descricao,
    p.maquina_id,
    p.tecnico_id,
    m.setor_id
FROM preventiva p
JOIN maquina m ON m.tenant_id = p.tenant_id AND m.id = p.maquina_id
WHERE p.id = $1
  AND p.tenant_id = $2
  AND p.ativa
  AND m.ativa
  AND p.proxima_data <= (now() AT TIME ZONE 'America/Sao_Paulo')::date
FOR UPDATE OF p
`

type ObterPreventivaVencidaParaAberturaParams struct {
	ID       int64
	TenantID int64
}

type ObterPreventivaVencidaParaAberturaRow struct {
	ID        int64
	TenantID  int64
	Descricao string
	MaquinaID int64
	TecnicoID *int64
	SetorID   int64
}

// Relê uma preventiva vencida sob lock, dentro da transação que vai abrir a
// solicitação e a OS dela. É a segunda metade de ListarPreventivasVencidas: a
// primeira varre, esta confirma e trava.
//
// ⚠️ O FOR UPDATE é o que impede duas réplicas do cron de abrirem o mesmo
// ciclo duas vezes, e substitui uq_preventiva_pendente (migration 000008). A
// sequência é: a réplica A trava a linha, insere solicitação + OS e avança
// proxima_data no mesmo commit; a réplica B fica bloqueada no SELECT até esse
// commit, e quando enfim lê a linha a data já está no futuro -- o WHERE não
// casa, a query devolve pgx.ErrNoRows e o job trata como "outra execução já
// pegou", não como falha. Sem o lock as duas leriam a data antiga e as duas
// escreveriam.
//
// FOR UPDATE OF p, não FOR UPDATE puro: o lock é da preventiva, que é a linha
// que muda. Travar `maquina` junto seria bloquear a edição da máquina pelo
// Administrador durante o job, sem necessidade nenhuma.
//
// Repete os filtros de ListarPreventivasVencidas de propósito (p.ativa,
// m.ativa, a data com fuso explícito) em vez de confiar no que a varredura já
// filtrou: entre uma e outra o Administrador pode ter desativado a preventiva
// ou a máquina. É a mesma releitura sob lock que ObterLojaParaEscrita faz
// antes de criar setor, pelo mesmo motivo.
//
// tecnico_id sai como *int64 (a coluna é nullable -- ver migration 000008) e o
// service recusa a preventiva sem técnico com erro visível, em vez de pular
// calado. Não force ::bigint aqui: o NULL é um estado real desta coluna, não
// uma folga do sqlc.
func (q *Queries) ObterPreventivaVencidaParaAbertura(ctx context.Context, arg ObterPreventivaVencidaParaAberturaParams) (ObterPreventivaVencidaParaAberturaRow, error) {
	row := q.db.QueryRow(ctx, obterPreventivaVencidaParaAbertura, arg.ID, arg.TenantID)
	var i ObterPreventivaVencidaParaAberturaRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Descricao,
		&i.MaquinaID,
		&i.TecnicoID,
		&i.SetorID,
	)
	return i, err
}
