// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	// Todos os campos editáveis de uma vez (o front manda o objeto inteiro no PUT).
	// `ativa` fica de fora: reativar não existe pela API, e desativar tem rota
	// própria -- ver DesativarEmpresaTerceirizada.
	AtualizarEmpresaTerceirizada(ctx context.Context, arg AtualizarEmpresaTerceirizadaParams) (EmpresaTerceirizada, error)
	AtualizarLoja(ctx context.Context, arg AtualizarLojaParams) (Loja, error)
	// setor_id entra no SET (diferente de AtualizarSetor, que ignora loja_id):
	// mover uma máquina de setor não arrasta setor/loja de ninguém, só o próprio
	// histórico dela, então mudar é uma operação válida, não um bug.
	AtualizarMaquina(ctx context.Context, arg AtualizarMaquinaParams) (Maquina, error)
	// Sem maquina_id, mesmo motivo de AtualizarSetor não mexer em loja_id: mover a
	// preventiva de máquina deixaria as solicitações que ela já gerou apontando
	// para uma máquina que não é mais a dela. O front manda o campo no PUT; o
	// service ignora.
	AtualizarPreventiva(ctx context.Context, arg AtualizarPreventivaParams) (Preventiva, error)
	AtualizarSenhaUsuario(ctx context.Context, arg AtualizarSenhaUsuarioParams) error
	// Sem loja_id: mudar o setor de loja moveria junto as máquinas, o histórico de
	// OS e o escopo de quem tem acesso a ele -- e ninguém pediu isso. Setor na
	// loja errada se resolve desativando e criando na certa.
	AtualizarSetor(ctx context.Context, arg AtualizarSetorParams) (Setor, error)
	// Sem senha_hash -- troca de senha tem query própria (AtualizarSenhaUsuario),
	// porque na edição ela é opcional (ver CadastrarUsuario: senha omitida mantém
	// o hash atual).
	AtualizarUsuario(ctx context.Context, arg AtualizarUsuarioParams) (Usuario, error)
	// Roda quando a preventiva vence e gera a solicitação automática: empurra a
	// próxima data em intervalo_dias a partir da data vencida (não a partir de
	// hoje) -- senão um ciclo processado com atraso arrastaria todos os seguintes.
	AvancarProximaData(ctx context.Context, arg AvancarProximaDataParams) (Preventiva, error)
	// Loja não é desativada por baixo dos setores: o escopo de acesso aponta pro
	// setor (usuario_escopo_setor), então setor ativo pendurado em loja inativa
	// continua dando acesso a uma loja que sumiu das listagens. Quem chama decide
	// se recusa ou se desativa os setores junto, mas precisa saber que existem.
	ContarSetoresAtivosDaLoja(ctx context.Context, arg ContarSetoresAtivosDaLojaParams) (int64, error)
	ContarSolicitacoesDoSolicitante(ctx context.Context, arg ContarSolicitacoesDoSolicitanteParams) (int64, error)
	ContarUsuarios(ctx context.Context, arg ContarUsuariosParams) (int64, error)
	// `chave` é a KEY do objeto no R2 (bucketR2.UploadFoto sobe o arquivo ANTES
	// de abrir a transação -- precisa da key para este INSERT -- e devolve só a
	// key, nunca URL: a leitura é sempre assinada na hora, ver
	// back-end/CLAUDE.md "R2 -- storage de anexos"). mime_type e tamanho_bytes
	// saem de graça do header do multipart, sem custo de I/O extra.
	CriarAnexoSolicitacao(ctx context.Context, arg CriarAnexoSolicitacaoParams) error
	// Empresa terceirizada é a prestadora externa que o TÉCNICO aciona quando
	// decide não resolver a OS internamente (front-end/CLAUDE.md item 9:
	// "terceirizar é decisão do Técnico"). Entidade simples: não pende de loja nem
	// de setor -- é do tenant inteiro, e por isso nenhuma listagem daqui filtra por
	// escopo, diferente de maquina/preventiva.
	//
	// Quem cadastra é o Administrador; quem consome é o Técnico, no
	// ModalAcionarTerceiro. Escrita só do administrador, leitura dos dois.
	//
	// Exclusão é soft delete (ativa = false), como em loja/setor/maquina:
	// ordem_servico.empresa_terceirizada_id aponta pra cá (fk_os_empresa_terceirizada,
	// composta por tenant), então apagar de verdade levaria junto o histórico de
	// quem executou o quê -- e a nota fiscal lançada em cima disso.
	//
	// ⚠️ A coluna é `ativa` (feminino), como em loja/maquina/preventiva -- e `ativo`
	// em usuario/setor.
	// Nome é único por tenant (uq_empresa_terceirizada_nome): duplicado volta 23505
	// e vira ErrDadoDuplicado no helper, sem switch em pgErr.Code no service.
	// especialidade e telefone são opcionais (NULL) -- o front tipa os dois como `?`.
	CriarEmpresaTerceirizada(ctx context.Context, arg CriarEmpresaTerceirizadaParams) (EmpresaTerceirizada, error)
	// Escopo de acesso (loja + setor) dos 4 perfis -- ver "3.8 Escopo de acesso
	// unificado" em docs/modelagem-banco-dados.md:
	//   Solicitante: 1 escopo, acesso_total_setores = false, exatamente 1 setor.
	//   Técnico:     N escopos, acesso_total_setores = true (sem linha de setor).
	//   Gestor:      N escopos, cada um acesso_total OU uma lista de setores.
	//   Administrador: nenhum escopo -- a ausência É o acesso total ao tenant.
	//
	// Editar substitui o conjunto inteiro (mesmo padrão de preventivas em
	// CadastrarMaquina): o service apaga tudo do usuário e recria, numa
	// transação -- não há UPDATE de escopo individual aqui de propósito.
	CriarEscopo(ctx context.Context, arg CriarEscopoParams) (UsuarioEscopo, error)
	CriarEscopoSetor(ctx context.Context, arg CriarEscopoSetorParams) error
	// Um INSERT por marcador (hoje só existe 'Afeta Produção' -- marcador_impacto
	// é ENUM de um valor só, associativa porque o contrato já troca uma lista).
	// Chamada em loop pelo service, na mesma transação da solicitação: sem
	// solicitação persistida ainda não há id para pendurar o impacto.
	CriarImpactoSolicitacao(ctx context.Context, arg CriarImpactoSolicitacaoParams) error
	// Loja é a unidade/filial dentro do tenant. Exclusão é sempre soft delete
	// (ativa = false) -- ver "Soft delete" em docs/modelagem-banco-dados.md:
	// máquina, setor e todo o histórico de OS apontam pra loja, então apagar de
	// verdade levaria o histórico junto.
	//
	// ⚠️ A coluna é `ativa` (feminino) na loja e `ativo` no setor/usuário.
	// Nome é único por tenant (uq_loja_tenant_nome): duplicado volta 23505 e
	// vira ErrDadoDuplicado no helper, sem switch em pgErr.Code no service.
	CriarLoja(ctx context.Context, arg CriarLojaParams) (Loja, error)
	// Máquina pertence a um setor (maquina só referencia setor_id -- a loja vem
	// por join, docs/modelagem-banco-dados.md). Exclusão é soft delete
	// (ativa = false), mesmo motivo de loja/setor: preventiva e o histórico de OS
	// apontam pra máquina.
	//
	// criticidade é o ENUM nivel_criticidade ('Baixa','Média','Alta', migration
	// 000004) e viaja com o mesmo texto que o front manda -- sem resolução
	// nome->id como em area_tecnico_id.
	//
	// foto_chave é a KEY do objeto no R2, nunca uma URL: a leitura é assinada na
	// hora (bucketR2.URLLeitura, ver back-end/CLAUDE.md "R2 -- storage de
	// anexos"). Entra em CriarMaquina porque o POST /maquinas sobe a foto na
	// mesma requisição; NULL quando o cliente não mandou nenhuma.
	//
	// Em AtualizarMaquina ela entra como COALESCE($11, foto_chave): sem foto nova
	// no multipart o valor chega NULL e a antiga fica. É o que a tela de edição
	// precisa -- o front só sabe *trocar* a foto, não remover (UploadFoto em
	// CadastrarMaquina.tsx), então NULL ali significa "não mexi", não "apague".
	// ⚠️ Trocar a foto deixa o objeto antigo órfão no bucket: ninguém apaga do R2.
	// É lixo barato e sem referência; se incomodar, o caminho é um DELETE do
	// objeto antigo depois do commit (nunca antes -- a transação pode voltar).
	//
	// ⚠️ As duas leituras (ObterMaquinaPorID, ListarMaquinas) trazem setor_nome,
	// loja_id e loja_nome por JOIN: o tipo Maquina do front exige setorNome e
	// lojaId, e maquina não guarda loja_id -- a loja só existe via setor. É o
	// padrão "nome vem denormalizado do servidor" de front-end/CLAUDE.md item 6:
	// a tela não monta o nome procurando numa lista à parte.
	//
	// Criar/Atualizar não conseguem fazer isso: RETURNING não enxerga tabela
	// juntada. Quem escrever o service resolve relendo por ObterMaquinaPorID
	// dentro da mesma transação -- é o único jeito de a resposta do POST/PUT ter
	// a mesma forma da resposta do GET.
	// fk_maquina_setor é composta (tenant_id, setor_id) -> setor (tenant_id, id):
	// o banco já recusa sozinho um setor de outro tenant, sem checagem extra
	// aqui.
	CriarMaquina(ctx context.Context, arg CriarMaquinaParams) (Maquina, error)
	// Nasce da aprovação do Gestor (POST /:id/abrir-os): só o INSERT mínimo que
	// faz a linha existir, ck_os_executor validando o resto (tecnico_id e
	// urgencia NOT NULL, e como tipo aqui nunca é 'terceiros' -- solicitacao_os
	// só produz 'maquinario'/'reparo' -- empresa_terceirizada_id e
	// terceiro_acionado_em ficam NULL, satisfazendo a metade "terceiros" do
	// CHECK por vacuidade). O ciclo de vida (iniciar/pausar/encerrar) é fase 2,
	// fora daqui.
	//
	// `urgencia` é o ENUM nivel_urgencia (migration 000007) -- sem
	// ObterUrgenciaPorNome/resolução nome->id: o front já manda o rótulo exato
	// ('Baixa'/'Média'/'Alta', front-end/src/tipos/ordemServico.ts) e o valor
	// viaja direto, mesmo padrão de `tipo`/`origem` em CriarSolicitacaoPreventiva.
	//
	// `tipo` é tipo_os, não tipo_solicitacao -- tipos Postgres diferentes com os
	// mesmos rótulos textuais; o service converte (solicitacao.Tipo vira o
	// parâmetro aqui), não este arquivo.
	//
	// `afeta_producao` vem do service, que já leu solicitacao_impacto: é aqui,
	// não em solicitacao_os, que o relógio de máquina parada (docs/modelagem,
	// "horas_parada só existe se afeta_producao") vai procurar o flag.
	//
	// RETURNING id, aberta_em (não só id): `aberta_em` é o `dataAbertura` da
	// resposta de POST /:id/abrir-os (OrdemServico do front) -- sai do DEFAULT
	// now() sem precisar reler a linha inteira, mesmo espírito de
	// CriarSolicitacaoMaquinario devolvendo `criado_em` junto do `id`.
	CriarOrdemServicoDeSolicitacao(ctx context.Context, arg CriarOrdemServicoDeSolicitacaoParams) (CriarOrdemServicoDeSolicitacaoRow, error)
	// Manutenção preventiva de uma máquina. Máquina exige pelo menos uma
	// (regra de negócio do front: esquemaCadastrarMaquina, preventivas min(1)), e
	// elas viajam na mesma requisição da máquina -- CriarPreventiva é chamada
	// tanto por POST /preventivas quanto por CadastrarMaquina, dentro da mesma
	// transação.
	//
	// Exclusão é soft delete (ativa = false), e aqui isso não é só convenção da
	// casa: fk_solicitacao_preventiva não tem ON DELETE, então toda preventiva que
	// já disparou uma solicitação automática (origem = 'preventiva') recusaria o
	// DELETE com 23503. Soft delete é o único caminho que não quebra depois do
	// primeiro ciclo vencer.
	//
	// ⚠️ `ativa` acumula dois sentidos: o alternador "Preventiva habilitada no
	// sistema" do ModalManutencaoPreventiva e o soft delete do DELETE
	// /preventivas/:id. Desabilitar pelo modal e excluir produzem o mesmo estado --
	// em ambos a preventiva para de vencer e some da listagem. Consistente com o
	// resto do sistema (não existe reativação pela API), mas é uma decisão, não um
	// acidente.
	//
	// proxima_data é `date`, não timestamptz: preventiva vence no dia, não na hora
	// (docs/modelagem-banco-dados.md, seção 3).
	// fk_preventiva_maquina é composta (tenant_id, maquina_id): o banco recusa
	// sozinho pendurar preventiva em máquina de outro tenant.
	// ck_intervalo (intervalo_dias > 0) volta 23514 e vira ErrConflitoIntegridade.
	CriarPreventiva(ctx context.Context, arg CriarPreventivaParams) (Preventiva, error)
	// Setor pertence a uma loja. Exclusão é soft delete (ativo = false) -- ver
	// "Soft delete" em docs/modelagem-banco-dados.md: máquina, solicitação e o
	// escopo de acesso apontam pro setor.
	//
	// Não existe lista fixa de setores: quem cadastra é o Administrador, com nome
	// livre e unicidade por loja (uq_setor_loja). Dois "Padaria" em lojas
	// diferentes são registros distintos de propósito -- por isso todo lugar
	// referencia setor_id, nunca o nome (front-end/CLAUDE.md item 6).
	// tenant_id vai explícito mesmo já estando implícito na loja: a FK composta
	// fk_setor_loja (tenant_id, loja_id) -> loja (tenant_id, id) só fecha com os
	// dois, e é ela que torna impossível pendurar um setor numa loja de outro
	// tenant -- o banco recusa, não depende de disciplina no service.
	CriarSetor(ctx context.Context, arg CriarSetorParams) (Setor, error)
	// POST /solicitacoes/maquinario. `tipo`/`origem` literais, mesmo motivo de
	// CriarSolicitacaoPreventiva: ck_solicitacao_alvo exige maquina_id e proíbe
	// item_descricao para 'maquinario', ck_origem exige solicitante_id para
	// 'solicitante'. setor_id vem da máquina escolhida (o service resolve via
	// ObterMaquinaPorID antes de chamar isto -- solicitação não guarda loja).
	//
	// RETURNING id, criado_em (não `*`): é só o que o service precisa para montar
	// a resposta via ObterSolicitacaoPorID logo em seguida, na mesma transação --
	// mesmo padrão de CadastrarMaquina relendo por Obter...PorID porque RETURNING
	// não enxerga tabela juntada (aqui nem precisaria do JOIN, mas mantém as duas
	// criações e a leitura com uma origem só de verdade).
	CriarSolicitacaoMaquinario(ctx context.Context, arg CriarSolicitacaoMaquinarioParams) (CriarSolicitacaoMaquinarioRow, error)
	// Solicitação de OS -- a fila que o Gestor avalia antes de existir Ordem de
	// Serviço. Nasce de duas origens (ck_origem amarra as duas colunas):
	//   'solicitante' -> alguém abriu pelo app, tem solicitante_id e foto;
	//   'preventiva'  -> venceu uma data no calendário, tem preventiva_id e
	//                    ninguém por trás (solicitante_id NULL, sem anexo).
	//
	// Este arquivo começa pelo caminho automático porque é o que o job de
	// preventiva vencida precisa. As leituras da fase 1 (GET /solicitacoes,
	// /minhas, /:id, /resumo) e as duas criações humanas (POST
	// /solicitacoes/maquinario e /reparo) entram aqui depois.
	// Insere a solicitação automática de uma preventiva vencida. Chamada só pelo
	// job (subcomando de CLI `preventivas-vencidas`), na mesma transação do
	// AvancarProximaData da preventiva de origem -- separadas, avançar a data com
	// o INSERT falhando pularia o ciclo em silêncio.
	//
	// `tipo` e `origem` são literais no SQL, não parâmetros, porque as constraints
	// não deixam variar:
	//   ck_solicitacao_alvo -> 'maquinario' exige maquina_id e PROÍBE
	//                          item_descricao (o oposto de 'reparo'). Preventiva é
	//                          sempre de uma máquina cadastrada;
	//   ck_origem           -> (origem = 'preventiva') = (preventiva_id IS NOT NULL)
	//                          e (origem = 'solicitante') = (solicitante_id IS NOT
	//                          NULL). Ou seja: solicitante_id não é "opcional" aqui,
	//                          é proibido -- por isso nem aparece na lista de
	//                          colunas.
	//
	// `status` fica no DEFAULT 'Pendente': a OS só nasce quando o Gestor aprova com
	// técnico e urgência (POST /solicitacoes/:id/abrir-os). Criar OS direto pularia
	// a aprovação, que é o ponto inteiro do fluxo.
	//
	// `setor_id` é NOT NULL e vem da máquina (a solicitação não guarda loja -- ela
	// sai via setor). Quem lê é ListarPreventivasVencidas, que já projeta
	// m.setor_id justamente para cá.
	//
	// Sem foto e sem ON CONFLICT, os dois de propósito:
	//   - trg_solicitacao_tem_foto exige anexo só para origem = 'solicitante'
	//     desde a migration 000005 -- antes dela este INSERT falhava no COMMIT;
	//   - uq_preventiva_pendente (índice único parcial em preventiva_id WHERE
	//     status = 'Pendente') é a rede contra execução duplicada do cron, e é ele
	//     -- não o NOT EXISTS da query que alimenta este INSERT -- quem garante a
	//     regra quando duas réplicas rodam juntas. Deixar o 23505 subir e o service
	//     tratar como benigno é mais simples que um ON CONFLICT com predicado
	//     parcial, que devolveria zero linhas e faria o :one virar pgx.ErrNoRows --
	//     um segundo caso de erro para o mesmo evento.
	// Os casts ::bigint em maquina_id e preventiva_id não são decoração: as duas
	// colunas são nullable no schema (precisam ser, para 'reparo' e para a origem
	// humana), e sem o cast o sqlc gera *int64 nos parâmetros. Aqui elas nunca são
	// nulas -- ck_solicitacao_alvo e ck_origem proíbem -- e ponteiro num job que
	// roda sozinho é só uma forma a mais de gravar NULL por engano.
	CriarSolicitacaoPreventiva(ctx context.Context, arg CriarSolicitacaoPreventivaParams) (int64, error)
	// POST /solicitacoes/reparo. Espelho da anterior para o outro lado de
	// ck_solicitacao_alvo: maquina_id fica NULL (nem entra na lista de colunas) e
	// item_descricao é obrigatório. setor_id aqui vem do escopo do solicitante
	// (ObterEscopoSessaoPorUsuario -- reparo não tem máquina para derivar loja),
	// não de uma query nova.
	CriarSolicitacaoReparo(ctx context.Context, arg CriarSolicitacaoReparoParams) (CriarSolicitacaoReparoRow, error)
	// Exclusão é sempre soft delete (ativo = false) -- ver "Soft delete" em
	// docs/modelagem-banco-dados.md: perde-se o cadastro, não o histórico de OS
	// vinculado ao usuário (solicitante/técnico/gestor).
	CriarUsuario(ctx context.Context, arg CriarUsuarioParams) (Usuario, error)
	DeletarEscoposPorUsuario(ctx context.Context, usuarioID int64) error
	// Roda antes de DeletarEscoposPorUsuario -- não há ON DELETE CASCADE entre
	// as duas tabelas.
	DeletarSetoresDosEscoposPorUsuario(ctx context.Context, usuarioID int64) error
	// :execrows e não :exec, mesmo motivo de DesativarLoja/DesativarMaquina: sem a
	// contagem de linhas, desativar um id que não existe (ou que é de outro tenant)
	// responderia sucesso igual a desativar um de verdade. linhas == 0 ->
	// ErrNaoEncontrado. Já desativada casa a linha e conta 1, então repetir é
	// idempotente -- e é assim que o front espera.
	//
	// Sem cheque de dependente antes, diferente de DesativarLoja (que recusa com
	// setor ativo): empresa terceirizada não tem filho. Ela é REFERENCIADA por
	// ordem_servico, mas como o delete é soft a FK nunca reclama, e a OS antiga
	// continua mostrando quem executou o serviço.
	DesativarEmpresaTerceirizada(ctx context.Context, arg DesativarEmpresaTerceirizadaParams) (int64, error)
	// :execrows e não :exec -- sem a contagem de linhas, desativar um id que não
	// existe (ou que é de outro tenant) responderia igual a desativar um de
	// verdade. Já desativada conta 1: o UPDATE casa a linha do mesmo jeito.
	DesativarLoja(ctx context.Context, arg DesativarLojaParams) (int64, error)
	// :execrows e não :exec, mesmo motivo de DesativarLoja/DesativarSetor: sem a
	// contagem de linhas, desativar um id que não existe (ou é de outro tenant)
	// responderia sucesso igual a desativar um de verdade.
	DesativarMaquina(ctx context.Context, arg DesativarMaquinaParams) (int64, error)
	// :execrows e não :exec, mesmo motivo de DesativarLoja/DesativarSetor: sem a
	// contagem de linhas, desativar um id inexistente (ou de outro tenant)
	// responderia sucesso igual a desativar um de verdade.
	DesativarPreventiva(ctx context.Context, arg DesativarPreventivaParams) (int64, error)
	// PUT /maquinas/:id substitui o conjunto inteiro de preventivas (não faz merge
	// incremental): o service desativa todas as da máquina e insere as novas, na
	// mesma transação -- mesmo padrão do escopo de acesso em AtualizarUsuario.
	//
	// Desativa em vez de deletar justamente por causa de fk_solicitacao_preventiva:
	// um DELETE aqui quebraria a edição de qualquer máquina cuja preventiva já
	// tivesse vencido uma vez.
	DesativarPreventivasDaMaquina(ctx context.Context, arg DesativarPreventivasDaMaquinaParams) error
	// :execrows pelo mesmo motivo de DesativarLoja: distinguir "desativei" de
	// "esse id não existe neste tenant".
	DesativarSetor(ctx context.Context, arg DesativarSetorParams) (int64, error)
	// Cascata em cima do soft delete: desativar a loja sem isto deixa setor ativo
	// pendurado em loja inativa, e o escopo de acesso aponta pro setor.
	DesativarSetoresDaLoja(ctx context.Context, arg DesativarSetoresDaLojaParams) (int64, error)
	// :execrows e não :exec -- sem a contagem de linhas, desativar um id que não
	// existe (ou que é de outro tenant) responderia 200 igualzinho a desativar um
	// de verdade. Já desativado conta 1 mesmo assim: o UPDATE casa a linha.
	DesativarUsuario(ctx context.Context, arg DesativarUsuarioParams) (int64, error)
	// Usado por ObterSessao: desativar uma empresa precisa derrubar as sessões
	// abertas dela, senão um token emitido antes continua valendo até expirar (8h).
	// Query própria em vez de JOIN em ObterUsuarioPorID porque aquela devolve
	// repository.Usuario, que montarSessao consome inteiro -- virar Row ali
	// espalharia a mudança por todo o caminho da sessão.
	EmpresaAtiva(ctx context.Context, id int64) (bool, error)
	// Só as ativas: a lista alimenta o select do ModalAcionarTerceiro, e oferecer
	// uma empresa desativada é oferecer o que o Administrador acabou de tirar do ar.
	//
	// Sem paginação e sem filtro de propósito -- servicoEmpresasTerceirizadas.listar()
	// não manda parâmetro nenhum e a tela do Administrador pagina no cliente
	// (front-end/CLAUDE.md item 12).
	ListarEmpresasTerceirizadas(ctx context.Context, tenantID int64) ([]EmpresaTerceirizada, error)
	// Sem paginação nem filtro de busca de propósito: /lojas devolve array simples
	// e o front pagina/filtra no cliente (front-end/CLAUDE.md item 12). Só
	// /usuarios e /solicitacoes/minhas paginam no servidor.
	ListarLojas(ctx context.Context, tenantID int64) ([]Loja, error)
	// setorId e lojaId são opcionais e combináveis (ParametrosListagemMaquinas no
	// front) -- NULL não filtra, mesmo padrão de ListarSetores. O JOIN com setor
	// é o que permite filtrar por loja, já que maquina não guarda loja_id.
	//
	// Filtra só por m.ativa, não por s.ativo/l.ativa: máquina em setor desativado
	// continua listada. É o comportamento certo enquanto DesativarSetor não
	// recusar (nem cascatear) com máquina ativa pendurada -- hoje não faz nem um
	// nem outro, diferente de DesativarLoja, que recusa com setor ativo.
	//
	// Array simples, sem paginação: o front pagina no cliente.
	ListarMaquinas(ctx context.Context, arg ListarMaquinasParams) ([]ListarMaquinasRow, error)
	// maquina_id é opcional (NULL não filtra): a aba "Manutenção Prev." do painel
	// do gestor lista tudo, e a tela de edição de máquina pede só as dela
	// (GET /preventivas?maquinaId=).
	//
	// `vencida` é calculado, nunca coluna -- o front só reage ao flag
	// (front-end/CLAUDE.md, ModalManutencaoPreventiva). A data de corte usa o fuso
	// de São Paulo explícito e não CURRENT_DATE: o container roda em UTC, e com
	// CURRENT_DATE uma preventiva apareceria vencida até 3h antes da virada do dia
	// no Brasil.
	//
	// Ordena por proxima_data: o que interessa na fila é o que vence antes, não a
	// ordem alfabética da máquina. Array simples, sem paginação -- o front pagina
	// no cliente.
	ListarPreventivas(ctx context.Context, arg ListarPreventivasParams) ([]ListarPreventivasRow, error)
	// Alimenta o job de abertura automática de solicitação (subcomando de CLI
	// `preventivas-vencidas`, chamado pelo Railway Cron -- ver "Abertura automática
	// de solicitação por preventiva" no CLAUDE.md). Cada linha daqui vira uma
	// solicitação com origem = 'preventiva' na fila do Gestor.
	//
	// ⚠️ É a única query do projeto SEM tenant_id no WHERE, e isso é proposital:
	// não há request, não há token, não há tenant. O job varre todos os tenants de
	// uma vez e o tenant_id viaja na linha, direto para o INSERT da solicitação.
	// Não "conserte" isso adicionando um filtro.
	//
	// Sem parâmetro nenhum, pelo mesmo motivo.
	//
	// Sobre o NOT EXISTS e uq_preventiva_pendente (índice único parcial em
	// solicitacao_os (preventiva_id) WHERE status = 'Pendente'), que fazem coisas
	// diferentes e é fácil confundir:
	//
	//   o índice é quem garante a regra -- uma preventiva não tem duas
	//   solicitações pendentes ao mesmo tempo (pode ter várias ao longo do tempo,
	//   uma por ciclo). Ele vale inclusive contra duas réplicas do cron rodando
	//   juntas, que é justamente o que a query sozinha não pega;
	//
	//   o NOT EXISTS evita o trabalho condenado. Enquanto o Gestor não converte
	//   nem rejeita, a preventiva continua com proxima_data no passado, então sem
	//   este filtro ela voltaria em toda execução para tomar 23505 no INSERT --
	//   uma transação inútil por preventiva parada na fila, todo dia.
	//
	// Ou seja: tirar o NOT EXISTS não corrompe nada (o service trata o 23505 como
	// benigno e a transação inteira volta), só desperdiça. Tirar o índice é que
	// quebra. É por isso que nenhum teste falha se este filtro sumir -- não tente
	// escrever um sem antes tornar o desperdício observável.
	//
	// m.ativa é igualmente obrigatório: DesativarMaquina NÃO desativa as
	// preventivas da máquina (maquina.sql, e não há ON DELETE/trigger fazendo
	// isso). Sem esse filtro, máquina desativada continuaria abrindo solicitação a
	// cada ciclo, para sempre, e não haveria como parar pela API -- não existe
	// reativação nem DELETE de linha em lugar nenhum.
	//
	// A data de corte usa fuso explícito e não CURRENT_DATE, mesmo motivo do
	// `vencida` nas outras duas queries: o container roda em UTC, e a preventiva
	// apareceria vencida até 3h antes da virada do dia no Brasil.
	//
	// Projeta só o que o INSERT da solicitação precisa (o setor_id vem da máquina:
	// solicitacao_os.setor_id é NOT NULL e a solicitação não guarda loja). Não usa
	// p.* como as outras: aqui ninguém monta resposta de contrato.
	ListarPreventivasVencidas(ctx context.Context) ([]ListarPreventivasVencidasRow, error)
	// loja_id é opcional (NULL não filtra) porque o front usa os dois modos: o
	// select em cascata pede os setores de uma loja (GET /setores?lojaId=) e
	// agruparPorEscopoGestor pede todos de uma vez, para nomear o cabeçalho de um
	// subgrupo vazio -- onde não há item de onde tirar o setorNome.
	//
	// Array simples, sem paginação: o front pagina no cliente (item 12).
	ListarSetores(ctx context.Context, arg ListarSetoresParams) ([]Setor, error)
	// GET /solicitacoes -- a fila do Gestor. Array simples, sem paginação (o
	// front pagina no cliente, mesmo padrão de ListarMaquinas/ListarPreventivas).
	//
	// status/tipo/lojaId/busca são combináveis e opcionais -- NULL não filtra.
	// Busca cobre descrição, nome da máquina e item do reparo (os dois campos que
	// a lista mostra como "alvo").
	//
	// Escopo no WHERE via EXISTS sobre usuario_escopo, mesmo bloco de
	// ListarMaquinas/ListarPreventivas: NULL é o administrador (não filtra), os
	// demais perfis só enxergam solicitação cujo setor eles alcançam.
	ListarSolicitacoes(ctx context.Context, arg ListarSolicitacoesParams) ([]ListarSolicitacoesRow, error)
	// GET /solicitacoes/minhas -- restrita ao próprio solicitante (nunca escopo:
	// é a lista pessoal, não a fila do gestor), paginada por LIMIT/OFFSET porque
	// model.RespostaPaginada exige os dois números (ContarSolicitacoesDoSolicitante
	// abaixo, mesmo WHERE, mesmo motivo de ContarUsuarios repetir o de
	// ListarUsuarios -- divergir dá total que não bate com a página).
	ListarSolicitacoesDoSolicitante(ctx context.Context, arg ListarSolicitacoesDoSolicitanteParams) ([]ListarSolicitacoesDoSolicitanteRow, error)
	// GET /tecnicos -- projeção somente-leitura sobre `usuario`, não tabela
	// própria: técnico é usuário com perfil 'tecnico'. Existe separada de
	// ListarUsuarios por três motivos, e o primeiro é o que obriga:
	//
	//  1. RBAC. /usuarios inteiro é do administrador, e quem precisa desta lista é
	//     o GESTOR, no select de "Técnico Responsável" do ModalAbrirOrdemServico --
	//     ele levaria 403 na outra rota.
	//  2. Forma. O tipo Tecnico do front pede `area` como NOME ("Refrigeração") e
	//     `lojasIds`; ListarUsuarios não junta area_tecnico e é paginada, enquanto
	//     o select quer array simples.
	//  3. Escrita continua em /usuarios (mesma tabela) -- duas superfícies de
	//     escrita deixariam o mesmo e-mail entrar duas vezes.
	//
	// O JOIN com area_tecnico é INNER porque ck_usuario_area_tecnico garante
	// area_tecnico_id NOT NULL exatamente para o perfil 'tecnico'.
	//
	// lojas_ids sai de array_agg com FILTER + COALESCE: técnico sem escopo nenhum
	// (não deve existir -- o cadastro exige loja) devolveria {NULL} sem o filtro, e
	// NULL sem o COALESCE. O cast final é o que faz o sqlc gerar []int64 em vez de
	// interface{} -- mesma armadilha do `vencida` em preventiva.sql.
	//
	// Os dois filtros são EXISTS e não JOIN, mesmo motivo de ListarUsuarios: com
	// JOIN o técnico apareceria uma vez por escopo que casa.
	//   loja_id           -- a loja da solicitação, mandada pelo modal do gestor.
	//   escopo_usuario_id -- quem chama (NULL = administrador, não filtra). Sem
	//                        isto um gestor lista nome e e-mail dos técnicos de
	//                        lojas que ele não enxerga.
	//
	// ⚠️ Os dois filtros vivem no MESMO EXISTS, sobre a mesma linha de
	// usuario_escopo, e isso é o ponto: separados, eles pediriam "atende a loja X"
	// E "divide alguma loja comigo" -- que não é a mesma coisa. Um gestor da Loja A
	// pedindo ?lojaId=B receberia o técnico que atende A e B, porque cada condição
	// passava por uma loja diferente. Tem que ser a mesma loja ligando os dois.
	// (Foi assim que a primeira versão saiu; o teste de integração pegou.)
	ListarTecnicos(ctx context.Context, arg ListarTecnicosParams) ([]ListarTecnicosRow, error)
	// Filtros combináveis: perfil, busca (nome/email) e loja_id são opcionais --
	// passe NULL para não filtrar por eles. Paginação por LIMIT/OFFSET, contagem
	// total em ContarUsuarios (RespostaPaginada exige os dois).
	//
	// loja_id filtra pelo escopo de acesso (usuario_escopo), com EXISTS e não
	// JOIN: usuário com N escopos apareceria N vezes e estouraria o LIMIT com
	// repetição. Administrador não tem escopo nenhum (a ausência É o acesso
	// total, 3.8), então some de qualquer listagem filtrada por loja -- que é o
	// certo: ele não pertence a loja alguma. ContarUsuarios repete o mesmo WHERE
	// de propósito; divergir entre as duas dá total que não bate com a página.
	ListarUsuarios(ctx context.Context, arg ListarUsuariosParams) ([]Usuario, error)
	// `AND status = 'Pendente'` no WHERE, não só no id: sem isso, abrir OS duas
	// vezes seguidas passaria a segunda também (uq_os_solicitacao pegaria no
	// INSERT de ordem_servico, mas tarde -- é melhor a solicitação já recusar
	// antes de gastar o INSERT). 0 linhas afetadas é como o service sabe que não
	// era Pendente e devolve ErrConflitoIntegridade, sem tentar o INSERT da OS.
	MarcarSolicitacaoConvertida(ctx context.Context, arg MarcarSolicitacaoConvertidaParams) (int64, error)
	ObterAnexosDaSolicitacao(ctx context.Context, solicitacaoID int64) ([]SolicitacaoAnexo, error)
	// Plural de propósito, mesmo motivo de ObterImpactosDasSolicitacoes: quem
	// monta uma página de solicitações busca os anexos de todas numa ida só.
	ObterAnexosDasSolicitacoes(ctx context.Context, solicitacaoIds []int64) ([]SolicitacaoAnexo, error)
	// Usado no cadastro de técnico: o front manda o nome da área (AreaTecnico em
	// front-end/src/tipos/tecnico.ts), o banco guarda o id em usuario.area_tecnico_id.
	ObterAreaTecnicoPorNome(ctx context.Context, arg ObterAreaTecnicoPorNomeParams) (int16, error)
	// GET /empresas: o tenant É a empresa (loja.tenant_id referencia empresa
	// direto), então a listagem que alimenta o select de Empresa no cadastro de
	// loja tem exatamente uma linha -- a do próprio tenant autenticado.
	ObterEmpresaPorID(ctx context.Context, id int64) (ObterEmpresaPorIDRow, error)
	ObterEmpresaPorSubdominio(ctx context.Context, subdominio string) (ObterEmpresaPorSubdominioRow, error)
	// Sem filtro de `ativa`, igual a ObterLojaPorID/ObterMaquinaPorID: a tela de
	// edição precisa ler o registro para preencher o formulário mesmo desativado.
	// Quem decide o que fazer com uma empresa inativa é o service.
	ObterEmpresaTerceirizadaPorID(ctx context.Context, arg ObterEmpresaTerceirizadaPorIDParams) (EmpresaTerceirizada, error)
	// Formato que o front consome direto em EscopoAcessoGestor[] (login/sessão):
	// um escopo por loja, com a lista de setor_id (vazia quando acesso_total_setores).
	ObterEscopoSessaoPorUsuario(ctx context.Context, usuarioID int64) ([]ObterEscopoSessaoPorUsuarioRow, error)
	ObterEscoposPorUsuario(ctx context.Context, usuarioID int64) ([]UsuarioEscopo, error)
	// Mesma forma de ObterEscopoSessaoPorUsuario, só que para vários usuários numa
	// ida só ao banco -- é o que ListarUsuarios usa para montar o escopo de uma
	// página inteira sem N+1.
	ObterEscoposSessaoPorUsuarios(ctx context.Context, usuarioIds []int64) ([]ObterEscoposSessaoPorUsuariosRow, error)
	// Filhos de uma solicitação só, usada por ObterSolicitacaoPorID (GET /:id, e
	// pela criação, que relê por ali dentro da mesma transação).
	ObterImpactosDaSolicitacao(ctx context.Context, solicitacaoID int64) ([]MarcadorImpacto, error)
	// Mesma forma da anterior, para uma página inteira numa ida só ao banco --
	// mesmo padrão de ObterEscoposSessaoPorUsuarios (usuario_escopo.sql): quem
	// lista usa a plural para não fazer N+1, uma query por solicitação da página.
	ObterImpactosDasSolicitacoes(ctx context.Context, solicitacaoIds []int64) ([]SolicitacaoImpacto, error)
	// Igual a ObterLojaPorID, com FOR SHARE: usada dentro da transação que cria
	// setor, para a loja não ser desativada entre o cheque de `ativa` e o INSERT.
	// FOR SHARE e não FOR UPDATE porque ninguém aqui altera a loja -- só precisa
	// impedir que ela mude enquanto o setor entra.
	ObterLojaParaEscrita(ctx context.Context, arg ObterLojaParaEscritaParams) (Loja, error)
	// Sem filtro de `ativa`, igual a ObterUsuarioPorID: a tela de edição precisa
	// ler o registro para preencher o formulário, e quem decide o que fazer com
	// uma loja desativada é o service.
	ObterLojaPorID(ctx context.Context, arg ObterLojaPorIDParams) (Loja, error)
	// Sem filtro de `ativa`, igual a ObterLojaPorID/ObterUsuarioPorID: a tela de
	// edição precisa ler o registro para preencher o formulário mesmo desativado.
	//
	// Os JOINs são INNER e não LEFT de propósito: setor_id e setor.loja_id são
	// NOT NULL com FK, então não existe máquina sem setor nem setor sem loja --
	// LEFT só faria o Go receber ponteiro em campo que nunca é nulo.
	ObterMaquinaPorID(ctx context.Context, arg ObterMaquinaPorIDParams) (ObterMaquinaPorIDRow, error)
	// Traz os denormalizados porque PreventivaListada (o retorno de POST e PUT
	// /preventivas, não só do GET) exige maquinaNome/setorId/setorNome/lojaId/
	// lojaNome. RETURNING não enxerga tabela juntada, então Criar/Atualizar releem
	// por aqui dentro da mesma transação para responder na forma do contrato.
	//
	// Sem filtro de `ativa`: a tela de edição precisa carregar o registro.
	ObterPreventivaPorID(ctx context.Context, arg ObterPreventivaPorIDParams) (ObterPreventivaPorIDRow, error)
	// GET /solicitacoes/resumo -- os três contadores da Home do Solicitante.
	// `abertas`/`emAndamento`/`concluidas` não são estados de solicitacao_os
	// (que só tem Pendente/Convertida/Rejeitada): são o status da OrdemServico
	// que ela virou, por isso o LEFT JOIN com ordem_servico. Uma solicitação
	// Pendente conta como "aberta" (ainda não foi nem avaliada); Rejeitada não
	// entra em nenhum balde, de propósito -- não é trabalho aberto nem
	// concluído, e a tela nem mostra essa categoria.
	//
	// count(*) FILTER (WHERE ...) e não três subqueries: uma passada só pela
	// tabela, sem repetir o FROM/WHERE três vezes.
	ObterResumoSolicitacoes(ctx context.Context, arg ObterResumoSolicitacoesParams) (ObterResumoSolicitacoesRow, error)
	// Diferente de ObterSetorPorID acima, que projeta só o que a sessão precisa:
	// esta devolve a linha inteira para a tela de edição.
	ObterSetorCompletoPorID(ctx context.Context, arg ObterSetorCompletoPorIDParams) (Setor, error)
	// Usado no login/sessão do solicitante: SessaoUsuario.setorNome vem daqui
	// (usuario_escopo guarda só o setor_id).
	ObterSetorPorID(ctx context.Context, arg ObterSetorPorIDParams) (ObterSetorPorIDRow, error)
	ObterSetoresPorEscopos(ctx context.Context, escopoIds []int64) ([]UsuarioEscopoSetor, error)
	// Usado no cadastro de usuário: NovoUsuarioPayload manda uma lista plana de
	// setores para N lojas, e setor pertence a uma loja só -- é daqui que sai a
	// distribuição de cada setor no escopo da loja certa.
	ObterSetoresPorIDs(ctx context.Context, arg ObterSetoresPorIDsParams) ([]ObterSetoresPorIDsRow, error)
	// Traz os denormalizados que SolicitacaoOS do front exige: maquinaNome/
	// maquinaCodigo/maquinaFotoUrl (reparo não tem máquina -- os três vêm NULL
	// via LEFT JOIN), setorNome/lojaId/lojaNome (sempre presentes -- toda
	// solicitação tem setor), solicitanteNome (NULL quando origem = 'preventiva')
	// e rejeitadoPorNome (NULL enquanto não rejeitada).
	//
	// Impactos e anexos ficam de fora de propósito, em vez de um array_agg aqui
	// dentro: mesmo padrão de usuário/escopo (ObterUsuarioPorID não traz o
	// escopo -- quem busca é uma query própria). Evita GROUP BY sobre `s.*` e
	// mantém uma única forma de buscar cada filho, reaproveitada tanto para uma
	// solicitação (aqui) quanto para uma página inteira delas (as `...Das...`
	// plurais abaixo).
	//
	// JOINs de setor/loja são INNER (NOT NULL, FK garante); máquina, solicitante
	// e rejeitado_por são LEFT (todos nullable no schema).
	//
	// escopo_usuario_id é opcional, mesmo `escopoDe(usuarioId, perfil)` de
	// ListarSolicitacoes -- e todo chamador manda ele, sempre: GET
	// /solicitacoes/:id (aberto a qualquer perfil) para não deixar um
	// Solicitante enumerar id e ler foto/descrição de outro setor, e
	// AbrirOS/Rejeitar (só gestor/administrador na rota) para o Gestor não agir
	// em solicitação de loja que ele não atende. NULL só quando `escopoDe`
	// devolve NULL, ou seja, para administrador -- ele não tem escopo, a
	// ausência É o acesso total. Fora do escopo cai em pgx.ErrNoRows como se o
	// id não existisse -- 404, nunca 403, mesmo critério de "filtro do cliente
	// estreita, nunca amplia".
	ObterSolicitacaoPorID(ctx context.Context, arg ObterSolicitacaoPorIDParams) (ObterSolicitacaoPorIDRow, error)
	// Usado no login: email é citext (case-insensitive) e único por tenant.
	ObterUsuarioPorEmail(ctx context.Context, arg ObterUsuarioPorEmailParams) (Usuario, error)
	ObterUsuarioPorID(ctx context.Context, arg ObterUsuarioPorIDParams) (Usuario, error)
	RegistrarUltimoAcesso(ctx context.Context, arg RegistrarUltimoAcessoParams) error
	// ck_rejeicao exige os três juntos (motivo, autor, instante) -- por isso
	// entram juntos aqui, nunca um UPDATE incremental. Mesmo filtro
	// `status = 'Pendente'` de MarcarSolicitacaoConvertida e pelo mesmo motivo:
	// não rejeitar (nem re-rejeitar) o que já saiu do estado inicial.
	RejeitarSolicitacao(ctx context.Context, arg RejeitarSolicitacaoParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
