// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	AtualizarSenhaUsuario(ctx context.Context, arg AtualizarSenhaUsuarioParams) error
	// Sem senha_hash -- troca de senha tem query própria (AtualizarSenhaUsuario),
	// porque na edição ela é opcional (ver CadastrarUsuario: senha omitida mantém
	// o hash atual).
	AtualizarUsuario(ctx context.Context, arg AtualizarUsuarioParams) (Usuario, error)
	ContarUsuarios(ctx context.Context, arg ContarUsuariosParams) (int64, error)
	// Escopo de acesso (loja + setor) dos 4 perfis -- ver "3.8 Escopo de acesso
	// unificado" em docs/modelagem-banco-dados.md:
	//   Solicitante: 1 escopo, acesso_total_setores = false, exatamente 1 setor.
	//   Técnico:     N escopos, acesso_total_setores = true (sem linha de setor).
	//   Gestor:      N escopos, cada um acesso_total OU uma lista de setores.
	//   Administrador: nenhum escopo -- a ausência É o acesso total ao tenant.
	//
	// Editar substitui o conjunto inteiro (mesmo padrão de preventivas em
	// CadastrarMaquina): o service apaga tudo do usuário e recria, numa
	// transação -- não há UPDATE de escopo individual aqui de propósito.
	CriarEscopo(ctx context.Context, arg CriarEscopoParams) (UsuarioEscopo, error)
	CriarEscopoSetor(ctx context.Context, arg CriarEscopoSetorParams) error
	// Exclusão é sempre soft delete (ativo = false) -- ver "Soft delete" em
	// docs/modelagem-banco-dados.md: perde-se o cadastro, não o histórico de OS
	// vinculado ao usuário (solicitante/técnico/gestor).
	CriarUsuario(ctx context.Context, arg CriarUsuarioParams) (Usuario, error)
	DeletarEscoposPorUsuario(ctx context.Context, usuarioID int64) error
	// Roda antes de DeletarEscoposPorUsuario -- não há ON DELETE CASCADE entre
	// as duas tabelas.
	DeletarSetoresDosEscoposPorUsuario(ctx context.Context, usuarioID int64) error
	// :execrows e não :exec -- sem a contagem de linhas, desativar um id que não
	// existe (ou que é de outro tenant) responderia 200 igualzinho a desativar um
	// de verdade. Já desativado conta 1 mesmo assim: o UPDATE casa a linha.
	DesativarUsuario(ctx context.Context, arg DesativarUsuarioParams) (int64, error)
	// Filtros combináveis: perfil, busca (nome/email) e loja_id são opcionais --
	// passe NULL para não filtrar por eles. Paginação por LIMIT/OFFSET, contagem
	// total em ContarUsuarios (RespostaPaginada exige os dois).
	//
	// loja_id filtra pelo escopo de acesso (usuario_escopo), com EXISTS e não
	// JOIN: usuário com N escopos apareceria N vezes e estouraria o LIMIT com
	// repetição. Administrador não tem escopo nenhum (a ausência É o acesso
	// total, 3.8), então some de qualquer listagem filtrada por loja -- que é o
	// certo: ele não pertence a loja alguma. ContarUsuarios repete o mesmo WHERE
	// de propósito; divergir entre as duas dá total que não bate com a página.
	ListarUsuarios(ctx context.Context, arg ListarUsuariosParams) ([]Usuario, error)
	// Usado no cadastro de técnico: o front manda o nome da área (AreaTecnico em
	// front-end/src/tipos/tecnico.ts), o banco guarda o id em usuario.area_tecnico_id.
	ObterAreaTecnicoPorNome(ctx context.Context, arg ObterAreaTecnicoPorNomeParams) (int16, error)
	ObterEmpresaPorSubdominio(ctx context.Context, subdominio string) (ObterEmpresaPorSubdominioRow, error)
	// Formato que o front consome direto em EscopoAcessoGestor[] (login/sessão):
	// um escopo por loja, com a lista de setor_id (vazia quando acesso_total_setores).
	ObterEscopoSessaoPorUsuario(ctx context.Context, usuarioID int64) ([]ObterEscopoSessaoPorUsuarioRow, error)
	ObterEscoposPorUsuario(ctx context.Context, usuarioID int64) ([]UsuarioEscopo, error)
	// Mesma forma de ObterEscopoSessaoPorUsuario, só que para vários usuários numa
	// ida só ao banco -- é o que ListarUsuarios usa para montar o escopo de uma
	// página inteira sem N+1.
	ObterEscoposSessaoPorUsuarios(ctx context.Context, usuarioIds []int64) ([]ObterEscoposSessaoPorUsuariosRow, error)
	// Usado no login/sessão do solicitante: SessaoUsuario.setorNome vem daqui
	// (usuario_escopo guarda só o setor_id).
	ObterSetorPorID(ctx context.Context, arg ObterSetorPorIDParams) (ObterSetorPorIDRow, error)
	ObterSetoresPorEscopos(ctx context.Context, escopoIds []int64) ([]UsuarioEscopoSetor, error)
	// Usado no cadastro de usuário: NovoUsuarioPayload manda uma lista plana de
	// setores para N lojas, e setor pertence a uma loja só -- é daqui que sai a
	// distribuição de cada setor no escopo da loja certa.
	ObterSetoresPorIDs(ctx context.Context, arg ObterSetoresPorIDsParams) ([]ObterSetoresPorIDsRow, error)
	// Usado no login: email é citext (case-insensitive) e único por tenant.
	ObterUsuarioPorEmail(ctx context.Context, arg ObterUsuarioPorEmailParams) (Usuario, error)
	ObterUsuarioPorID(ctx context.Context, arg ObterUsuarioPorIDParams) (Usuario, error)
	RegistrarUltimoAcesso(ctx context.Context, arg RegistrarUltimoAcessoParams) error
}

var _ Querier = (*Queries)(nil)
