// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setor.sql

package repository

import (
	"context"
)

const obterSetorPorID = `-- name: ObterSetorPorID :one
SELECT id, nome, loja_id FROM setor
WHERE id = $1 AND tenant_id = $2
`

type ObterSetorPorIDParams struct {
	ID       int64
	TenantID int64
}

type ObterSetorPorIDRow struct {
	ID     int64
	Nome   string
	LojaID int64
}

// Usado no login/sessão do solicitante: SessaoUsuario.setorNome vem daqui
// (usuario_escopo guarda só o setor_id).
func (q *Queries) ObterSetorPorID(ctx context.Context, arg ObterSetorPorIDParams) (ObterSetorPorIDRow, error) {
	row := q.db.QueryRow(ctx, obterSetorPorID, arg.ID, arg.TenantID)
	var i ObterSetorPorIDRow
	err := row.Scan(&i.ID, &i.Nome, &i.LojaID)
	return i, err
}
