// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setor.sql

package repository

import (
	"context"
)

const atualizarSetor = `-- name: AtualizarSetor :one
UPDATE setor
SET nome = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, loja_id, nome, ativo, criado_em
`

type AtualizarSetorParams struct {
	ID       int64
	TenantID int64
	Nome     string
}

// Sem loja_id: mudar o setor de loja moveria junto as máquinas, o histórico de
// OS e o escopo de quem tem acesso a ele -- e ninguém pediu isso. Setor na
// loja errada se resolve desativando e criando na certa.
func (q *Queries) AtualizarSetor(ctx context.Context, arg AtualizarSetorParams) (Setor, error) {
	row := q.db.QueryRow(ctx, atualizarSetor, arg.ID, arg.TenantID, arg.Nome)
	var i Setor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LojaID,
		&i.Nome,
		&i.Ativo,
		&i.CriadoEm,
	)
	return i, err
}

const criarSetor = `-- name: CriarSetor :one

INSERT INTO setor (tenant_id, loja_id, nome)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, loja_id, nome, ativo, criado_em
`

type CriarSetorParams struct {
	TenantID int64
	LojaID   int64
	Nome     string
}

// Setor pertence a uma loja. Exclusão é soft delete (ativo = false) -- ver
// "Soft delete" em docs/modelagem-banco-dados.md: máquina, solicitação e o
// escopo de acesso apontam pro setor.
//
// Não existe lista fixa de setores: quem cadastra é o Administrador, com nome
// livre e unicidade por loja (uq_setor_loja). Dois "Padaria" em lojas
// diferentes são registros distintos de propósito -- por isso todo lugar
// referencia setor_id, nunca o nome (front-end/CLAUDE.md item 6).
// tenant_id vai explícito mesmo já estando implícito na loja: a FK composta
// fk_setor_loja (tenant_id, loja_id) -> loja (tenant_id, id) só fecha com os
// dois, e é ela que torna impossível pendurar um setor numa loja de outro
// tenant -- o banco recusa, não depende de disciplina no service.
func (q *Queries) CriarSetor(ctx context.Context, arg CriarSetorParams) (Setor, error) {
	row := q.db.QueryRow(ctx, criarSetor, arg.TenantID, arg.LojaID, arg.Nome)
	var i Setor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LojaID,
		&i.Nome,
		&i.Ativo,
		&i.CriadoEm,
	)
	return i, err
}

const desativarSetor = `-- name: DesativarSetor :execrows
UPDATE setor
SET ativo = false
WHERE id = $1 AND tenant_id = $2
`

type DesativarSetorParams struct {
	ID       int64
	TenantID int64
}

// :execrows pelo mesmo motivo de DesativarLoja: distinguir "desativei" de
// "esse id não existe neste tenant".
func (q *Queries) DesativarSetor(ctx context.Context, arg DesativarSetorParams) (int64, error) {
	result, err := q.db.Exec(ctx, desativarSetor, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const desativarSetoresDaLoja = `-- name: DesativarSetoresDaLoja :execrows
UPDATE setor
SET ativo = false
WHERE tenant_id = $1 AND loja_id = $2
`

type DesativarSetoresDaLojaParams struct {
	TenantID int64
	LojaID   int64
}

// Cascata em cima do soft delete: desativar a loja sem isto deixa setor ativo
// pendurado em loja inativa, e o escopo de acesso aponta pro setor.
func (q *Queries) DesativarSetoresDaLoja(ctx context.Context, arg DesativarSetoresDaLojaParams) (int64, error) {
	result, err := q.db.Exec(ctx, desativarSetoresDaLoja, arg.TenantID, arg.LojaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarSetores = `-- name: ListarSetores :many
SELECT id, tenant_id, loja_id, nome, ativo, criado_em FROM setor
WHERE tenant_id = $1
  AND ativo
  AND ($2::bigint IS NULL OR loja_id = $2)
ORDER BY nome
`

type ListarSetoresParams struct {
	TenantID int64
	LojaID   *int64
}

// loja_id é opcional (NULL não filtra) porque o front usa os dois modos: o
// select em cascata pede os setores de uma loja (GET /setores?lojaId=) e
// agruparPorEscopoGestor pede todos de uma vez, para nomear o cabeçalho de um
// subgrupo vazio -- onde não há item de onde tirar o setorNome.
//
// Array simples, sem paginação: o front pagina no cliente (item 12).
func (q *Queries) ListarSetores(ctx context.Context, arg ListarSetoresParams) ([]Setor, error) {
	rows, err := q.db.Query(ctx, listarSetores, arg.TenantID, arg.LojaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setor
	for rows.Next() {
		var i Setor
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LojaID,
			&i.Nome,
			&i.Ativo,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterSetorCompletoPorID = `-- name: ObterSetorCompletoPorID :one
SELECT id, tenant_id, loja_id, nome, ativo, criado_em FROM setor
WHERE id = $1 AND tenant_id = $2
`

type ObterSetorCompletoPorIDParams struct {
	ID       int64
	TenantID int64
}

// Diferente de ObterSetorPorID acima, que projeta só o que a sessão precisa:
// esta devolve a linha inteira para a tela de edição.
func (q *Queries) ObterSetorCompletoPorID(ctx context.Context, arg ObterSetorCompletoPorIDParams) (Setor, error) {
	row := q.db.QueryRow(ctx, obterSetorCompletoPorID, arg.ID, arg.TenantID)
	var i Setor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LojaID,
		&i.Nome,
		&i.Ativo,
		&i.CriadoEm,
	)
	return i, err
}

const obterSetorPorID = `-- name: ObterSetorPorID :one
SELECT id, nome, loja_id FROM setor
WHERE id = $1 AND tenant_id = $2
`

type ObterSetorPorIDParams struct {
	ID       int64
	TenantID int64
}

type ObterSetorPorIDRow struct {
	ID     int64
	Nome   string
	LojaID int64
}

// Usado no login/sessão do solicitante: SessaoUsuario.setorNome vem daqui
// (usuario_escopo guarda só o setor_id).
func (q *Queries) ObterSetorPorID(ctx context.Context, arg ObterSetorPorIDParams) (ObterSetorPorIDRow, error) {
	row := q.db.QueryRow(ctx, obterSetorPorID, arg.ID, arg.TenantID)
	var i ObterSetorPorIDRow
	err := row.Scan(&i.ID, &i.Nome, &i.LojaID)
	return i, err
}

const obterSetoresPorIDs = `-- name: ObterSetoresPorIDs :many
SELECT id, loja_id FROM setor
WHERE id = ANY($1::bigint[]) AND tenant_id = $2
`

type ObterSetoresPorIDsParams struct {
	Ids      []int64
	TenantID int64
}

type ObterSetoresPorIDsRow struct {
	ID     int64
	LojaID int64
}

// Usado no cadastro de usuário: NovoUsuarioPayload manda uma lista plana de
// setores para N lojas, e setor pertence a uma loja só -- é daqui que sai a
// distribuição de cada setor no escopo da loja certa.
func (q *Queries) ObterSetoresPorIDs(ctx context.Context, arg ObterSetoresPorIDsParams) ([]ObterSetoresPorIDsRow, error) {
	rows, err := q.db.Query(ctx, obterSetoresPorIDs, arg.Ids, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObterSetoresPorIDsRow
	for rows.Next() {
		var i ObterSetoresPorIDsRow
		if err := rows.Scan(&i.ID, &i.LojaID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
