// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: solicitacao_os.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const contarSolicitacoesDoSolicitante = `-- name: ContarSolicitacoesDoSolicitante :one
SELECT count(*)
FROM solicitacao_os s
LEFT JOIN maquina m ON m.tenant_id = s.tenant_id AND m.id = s.maquina_id
WHERE s.tenant_id = $1
  AND s.solicitante_id = $2
  AND ($3::status_solicitacao IS NULL OR s.status = $3)
  AND (
    $4::text IS NULL
    OR s.descricao ILIKE '%' || $4 || '%'
    OR m.nome ILIKE '%' || $4 || '%'
    OR s.item_descricao ILIKE '%' || $4 || '%'
  )
`

type ContarSolicitacoesDoSolicitanteParams struct {
	TenantID      int64
	SolicitanteID *int64
	Status        *StatusSolicitacao
	Busca         *string
}

func (q *Queries) ContarSolicitacoesDoSolicitante(ctx context.Context, arg ContarSolicitacoesDoSolicitanteParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarSolicitacoesDoSolicitante,
		arg.TenantID,
		arg.SolicitanteID,
		arg.Status,
		arg.Busca,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarAnexoSolicitacao = `-- name: CriarAnexoSolicitacao :exec
INSERT INTO solicitacao_anexo (solicitacao_id, tipo, chave, mime_type, tamanho_bytes)
VALUES ($1, $2, $3, $4, $5)
`

type CriarAnexoSolicitacaoParams struct {
	SolicitacaoID int64
	Tipo          TipoAnexo
	Chave         string
	MimeType      string
	TamanhoBytes  int64
}

// `chave` é a KEY do objeto no R2 (bucketR2.UploadFoto sobe o arquivo ANTES
// de abrir a transação -- precisa da key para este INSERT -- e devolve só a
// key, nunca URL: a leitura é sempre assinada na hora, ver
// back-end/CLAUDE.md "R2 -- storage de anexos"). mime_type e tamanho_bytes
// saem de graça do header do multipart, sem custo de I/O extra.
func (q *Queries) CriarAnexoSolicitacao(ctx context.Context, arg CriarAnexoSolicitacaoParams) error {
	_, err := q.db.Exec(ctx, criarAnexoSolicitacao,
		arg.SolicitacaoID,
		arg.Tipo,
		arg.Chave,
		arg.MimeType,
		arg.TamanhoBytes,
	)
	return err
}

const criarImpactoSolicitacao = `-- name: CriarImpactoSolicitacao :exec
INSERT INTO solicitacao_impacto (solicitacao_id, marcador) VALUES ($1, $2)
`

type CriarImpactoSolicitacaoParams struct {
	SolicitacaoID int64
	Marcador      MarcadorImpacto
}

// Um INSERT por marcador (hoje só existe 'Afeta Produção' -- marcador_impacto
// é ENUM de um valor só, associativa porque o contrato já troca uma lista).
// Chamada em loop pelo service, na mesma transação da solicitação: sem
// solicitação persistida ainda não há id para pendurar o impacto.
func (q *Queries) CriarImpactoSolicitacao(ctx context.Context, arg CriarImpactoSolicitacaoParams) error {
	_, err := q.db.Exec(ctx, criarImpactoSolicitacao, arg.SolicitacaoID, arg.Marcador)
	return err
}

const criarOrdemServicoDeSolicitacao = `-- name: CriarOrdemServicoDeSolicitacao :one
INSERT INTO ordem_servico (tenant_id, solicitacao_id, tipo, tecnico_id, urgencia, aberta_por_id, afeta_producao)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, aberta_em
`

type CriarOrdemServicoDeSolicitacaoParams struct {
	TenantID      int64
	SolicitacaoID int64
	Tipo          TipoOs
	TecnicoID     int64
	Urgencia      NivelUrgencia
	AbertaPorID   int64
	AfetaProducao bool
}

type CriarOrdemServicoDeSolicitacaoRow struct {
	ID       int64
	AbertaEm pgtype.Timestamptz
}

// Nasce da aprovação do Gestor (POST /:id/abrir-os): só o INSERT mínimo que
// faz a linha existir, ck_os_executor validando o resto (tecnico_id e
// urgencia NOT NULL, e como tipo aqui nunca é 'terceiros' -- solicitacao_os
// só produz 'maquinario'/'reparo' -- empresa_terceirizada_id e
// terceiro_acionado_em ficam NULL, satisfazendo a metade "terceiros" do
// CHECK por vacuidade). O ciclo de vida (iniciar/pausar/encerrar) é fase 2,
// fora daqui.
//
// `urgencia` é o ENUM nivel_urgencia (migration 000007) -- sem
// ObterUrgenciaPorNome/resolução nome->id: o front já manda o rótulo exato
// ('Baixa'/'Média'/'Alta', front-end/src/tipos/ordemServico.ts) e o valor
// viaja direto, mesmo padrão de `tipo`/`origem` em CriarSolicitacaoPreventiva.
//
// `tipo` é tipo_os, não tipo_solicitacao -- tipos Postgres diferentes com os
// mesmos rótulos textuais; o service converte (solicitacao.Tipo vira o
// parâmetro aqui), não este arquivo.
//
// `afeta_producao` vem do service, que já leu solicitacao_impacto: é aqui,
// não em solicitacao_os, que o relógio de máquina parada (docs/modelagem,
// "horas_parada só existe se afeta_producao") vai procurar o flag.
//
// RETURNING id, aberta_em (não só id): `aberta_em` é o `dataAbertura` da
// resposta de POST /:id/abrir-os (OrdemServico do front) -- sai do DEFAULT
// now() sem precisar reler a linha inteira, mesmo espírito de
// CriarSolicitacaoMaquinario devolvendo `criado_em` junto do `id`.
func (q *Queries) CriarOrdemServicoDeSolicitacao(ctx context.Context, arg CriarOrdemServicoDeSolicitacaoParams) (CriarOrdemServicoDeSolicitacaoRow, error) {
	row := q.db.QueryRow(ctx, criarOrdemServicoDeSolicitacao,
		arg.TenantID,
		arg.SolicitacaoID,
		arg.Tipo,
		arg.TecnicoID,
		arg.Urgencia,
		arg.AbertaPorID,
		arg.AfetaProducao,
	)
	var i CriarOrdemServicoDeSolicitacaoRow
	err := row.Scan(&i.ID, &i.AbertaEm)
	return i, err
}

const criarSolicitacaoMaquinario = `-- name: CriarSolicitacaoMaquinario :one
INSERT INTO solicitacao_os (tenant_id, tipo, maquina_id, setor_id, solicitante_id, origem, descricao)
VALUES (
    $1,
    'maquinario',
    $2,
    $3,
    $4,
    'solicitante',
    $5
)
RETURNING id, criado_em
`

type CriarSolicitacaoMaquinarioParams struct {
	TenantID      int64
	MaquinaID     *int64
	SetorID       int64
	SolicitanteID *int64
	Descricao     string
}

type CriarSolicitacaoMaquinarioRow struct {
	ID       int64
	CriadoEm pgtype.Timestamptz
}

// POST /solicitacoes/maquinario. `tipo`/`origem` literais, mesmo motivo de
// CriarSolicitacaoPreventiva: ck_solicitacao_alvo exige maquina_id e proíbe
// item_descricao para 'maquinario', ck_origem exige solicitante_id para
// 'solicitante'. setor_id vem da máquina escolhida (o service resolve via
// ObterMaquinaPorID antes de chamar isto -- solicitação não guarda loja).
//
// RETURNING id, criado_em (não `*`): é só o que o service precisa para montar
// a resposta via ObterSolicitacaoPorID logo em seguida, na mesma transação --
// mesmo padrão de CadastrarMaquina relendo por Obter...PorID porque RETURNING
// não enxerga tabela juntada (aqui nem precisaria do JOIN, mas mantém as duas
// criações e a leitura com uma origem só de verdade).
func (q *Queries) CriarSolicitacaoMaquinario(ctx context.Context, arg CriarSolicitacaoMaquinarioParams) (CriarSolicitacaoMaquinarioRow, error) {
	row := q.db.QueryRow(ctx, criarSolicitacaoMaquinario,
		arg.TenantID,
		arg.MaquinaID,
		arg.SetorID,
		arg.SolicitanteID,
		arg.Descricao,
	)
	var i CriarSolicitacaoMaquinarioRow
	err := row.Scan(&i.ID, &i.CriadoEm)
	return i, err
}

const criarSolicitacaoPreventiva = `-- name: CriarSolicitacaoPreventiva :one

INSERT INTO solicitacao_os (tenant_id, tipo, maquina_id, setor_id, preventiva_id, origem, descricao)
VALUES (
    $1,
    'maquinario',
    $2::bigint,
    $3,
    $4::bigint,
    'preventiva',
    $5
)
RETURNING id
`

type CriarSolicitacaoPreventivaParams struct {
	TenantID     int64
	MaquinaID    int64
	SetorID      int64
	PreventivaID int64
	Descricao    string
}

// Solicitação de OS -- a fila que o Gestor avalia antes de existir Ordem de
// Serviço. Nasce de duas origens (ck_origem amarra as duas colunas):
//
//	'solicitante' -> alguém abriu pelo app, tem solicitante_id e foto;
//	'preventiva'  -> venceu uma data no calendário, tem preventiva_id e
//	                 ninguém por trás (solicitante_id NULL, sem anexo).
//
// Este arquivo começa pelo caminho automático porque é o que o job de
// preventiva vencida precisa. As leituras da fase 1 (GET /solicitacoes,
// /minhas, /:id, /resumo) e as duas criações humanas (POST
// /solicitacoes/maquinario e /reparo) entram aqui depois.
// Insere a solicitação automática de uma preventiva vencida. Chamada só pelo
// job (subcomando de CLI `preventivas-vencidas`), na mesma transação do
// AvancarProximaData da preventiva de origem -- separadas, avançar a data com
// o INSERT falhando pularia o ciclo em silêncio.
//
// `tipo` e `origem` são literais no SQL, não parâmetros, porque as constraints
// não deixam variar:
//
//	ck_solicitacao_alvo -> 'maquinario' exige maquina_id e PROÍBE
//	                       item_descricao (o oposto de 'reparo'). Preventiva é
//	                       sempre de uma máquina cadastrada;
//	ck_origem           -> (origem = 'preventiva') = (preventiva_id IS NOT NULL)
//	                       e (origem = 'solicitante') = (solicitante_id IS NOT
//	                       NULL). Ou seja: solicitante_id não é "opcional" aqui,
//	                       é proibido -- por isso nem aparece na lista de
//	                       colunas.
//
// `status` fica no DEFAULT 'Pendente': a OS só nasce quando o Gestor aprova com
// técnico e urgência (POST /solicitacoes/:id/abrir-os). Criar OS direto pularia
// a aprovação, que é o ponto inteiro do fluxo.
//
// `setor_id` é NOT NULL e vem da máquina (a solicitação não guarda loja -- ela
// sai via setor). Quem lê é ListarPreventivasVencidas, que já projeta
// m.setor_id justamente para cá.
//
// Sem foto e sem ON CONFLICT, os dois de propósito:
//   - trg_solicitacao_tem_foto exige anexo só para origem = 'solicitante'
//     desde a migration 000005 -- antes dela este INSERT falhava no COMMIT;
//   - uq_preventiva_pendente (índice único parcial em preventiva_id WHERE
//     status = 'Pendente') é a rede contra execução duplicada do cron, e é ele
//     -- não o NOT EXISTS da query que alimenta este INSERT -- quem garante a
//     regra quando duas réplicas rodam juntas. Deixar o 23505 subir e o service
//     tratar como benigno é mais simples que um ON CONFLICT com predicado
//     parcial, que devolveria zero linhas e faria o :one virar pgx.ErrNoRows --
//     um segundo caso de erro para o mesmo evento.
//
// Os casts ::bigint em maquina_id e preventiva_id não são decoração: as duas
// colunas são nullable no schema (precisam ser, para 'reparo' e para a origem
// humana), e sem o cast o sqlc gera *int64 nos parâmetros. Aqui elas nunca são
// nulas -- ck_solicitacao_alvo e ck_origem proíbem -- e ponteiro num job que
// roda sozinho é só uma forma a mais de gravar NULL por engano.
func (q *Queries) CriarSolicitacaoPreventiva(ctx context.Context, arg CriarSolicitacaoPreventivaParams) (int64, error) {
	row := q.db.QueryRow(ctx, criarSolicitacaoPreventiva,
		arg.TenantID,
		arg.MaquinaID,
		arg.SetorID,
		arg.PreventivaID,
		arg.Descricao,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const criarSolicitacaoReparo = `-- name: CriarSolicitacaoReparo :one
INSERT INTO solicitacao_os (tenant_id, tipo, item_descricao, setor_id, solicitante_id, origem, descricao)
VALUES (
    $1,
    'reparo',
    $2,
    $3,
    $4,
    'solicitante',
    $5
)
RETURNING id, criado_em
`

type CriarSolicitacaoReparoParams struct {
	TenantID      int64
	ItemDescricao *string
	SetorID       int64
	SolicitanteID *int64
	Descricao     string
}

type CriarSolicitacaoReparoRow struct {
	ID       int64
	CriadoEm pgtype.Timestamptz
}

// POST /solicitacoes/reparo. Espelho da anterior para o outro lado de
// ck_solicitacao_alvo: maquina_id fica NULL (nem entra na lista de colunas) e
// item_descricao é obrigatório. setor_id aqui vem do escopo do solicitante
// (ObterEscopoSessaoPorUsuario -- reparo não tem máquina para derivar loja),
// não de uma query nova.
func (q *Queries) CriarSolicitacaoReparo(ctx context.Context, arg CriarSolicitacaoReparoParams) (CriarSolicitacaoReparoRow, error) {
	row := q.db.QueryRow(ctx, criarSolicitacaoReparo,
		arg.TenantID,
		arg.ItemDescricao,
		arg.SetorID,
		arg.SolicitanteID,
		arg.Descricao,
	)
	var i CriarSolicitacaoReparoRow
	err := row.Scan(&i.ID, &i.CriadoEm)
	return i, err
}

const listarSolicitacoes = `-- name: ListarSolicitacoes :many
SELECT
    s.id, s.tenant_id, s.tipo, s.maquina_id, s.item_descricao, s.setor_id, s.solicitante_id, s.preventiva_id, s.status, s.origem, s.descricao, s.motivo_rejeicao, s.rejeitado_por_id, s.rejeitada_em, s.criado_em,
    m.nome AS maquina_nome,
    m.numero_patrimonio AS maquina_codigo,
    m.foto_chave AS maquina_foto_chave,
    sc.nome AS setor_nome,
    sc.loja_id,
    l.nome AS loja_nome,
    sol.nome AS solicitante_nome,
    rej.nome AS rejeitado_por_nome
FROM solicitacao_os s
JOIN setor sc ON sc.tenant_id = s.tenant_id AND sc.id = s.setor_id
JOIN loja  l  ON l.tenant_id = sc.tenant_id AND l.id = sc.loja_id
LEFT JOIN maquina m   ON m.tenant_id = s.tenant_id AND m.id = s.maquina_id
LEFT JOIN usuario sol ON sol.tenant_id = s.tenant_id AND sol.id = s.solicitante_id
LEFT JOIN usuario rej ON rej.tenant_id = s.tenant_id AND rej.id = s.rejeitado_por_id
WHERE s.tenant_id = $1
  AND ($2::status_solicitacao IS NULL OR s.status = $2)
  AND ($3::tipo_solicitacao IS NULL OR s.tipo = $3)
  AND ($4::bigint IS NULL OR sc.loja_id = $4)
  AND (
    $5::text IS NULL
    OR s.descricao ILIKE '%' || $5 || '%'
    OR m.nome ILIKE '%' || $5 || '%'
    OR s.item_descricao ILIKE '%' || $5 || '%'
  )
  AND (
    $6::bigint IS NULL
    OR EXISTS (
      SELECT 1
      FROM usuario_escopo ue
      LEFT JOIN usuario_escopo_setor ues ON ues.escopo_id = ue.id
      WHERE ue.usuario_id = $6
        AND ue.loja_id = sc.loja_id
        AND (ue.acesso_total_setores OR ues.setor_id = s.setor_id)
    )
  )
ORDER BY s.criado_em DESC
`

type ListarSolicitacoesParams struct {
	TenantID        int64
	Status          *StatusSolicitacao
	Tipo            *TipoSolicitacao
	LojaID          *int64
	Busca           *string
	EscopoUsuarioID *int64
}

type ListarSolicitacoesRow struct {
	ID               int64
	TenantID         int64
	Tipo             TipoSolicitacao
	MaquinaID        *int64
	ItemDescricao    *string
	SetorID          int64
	SolicitanteID    *int64
	PreventivaID     *int64
	Status           StatusSolicitacao
	Origem           OrigemSolicitacao
	Descricao        string
	MotivoRejeicao   *string
	RejeitadoPorID   *int64
	RejeitadaEm      pgtype.Timestamptz
	CriadoEm         pgtype.Timestamptz
	MaquinaNome      *string
	MaquinaCodigo    *string
	MaquinaFotoChave *string
	SetorNome        string
	LojaID           int64
	LojaNome         string
	SolicitanteNome  *string
	RejeitadoPorNome *string
}

// GET /solicitacoes -- a fila do Gestor. Array simples, sem paginação (o
// front pagina no cliente, mesmo padrão de ListarMaquinas/ListarPreventivas).
//
// status/tipo/lojaId/busca são combináveis e opcionais -- NULL não filtra.
// Busca cobre descrição, nome da máquina e item do reparo (os dois campos que
// a lista mostra como "alvo").
//
// Escopo no WHERE via EXISTS sobre usuario_escopo, mesmo bloco de
// ListarMaquinas/ListarPreventivas: NULL é o administrador (não filtra), os
// demais perfis só enxergam solicitação cujo setor eles alcançam.
func (q *Queries) ListarSolicitacoes(ctx context.Context, arg ListarSolicitacoesParams) ([]ListarSolicitacoesRow, error) {
	rows, err := q.db.Query(ctx, listarSolicitacoes,
		arg.TenantID,
		arg.Status,
		arg.Tipo,
		arg.LojaID,
		arg.Busca,
		arg.EscopoUsuarioID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarSolicitacoesRow
	for rows.Next() {
		var i ListarSolicitacoesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Tipo,
			&i.MaquinaID,
			&i.ItemDescricao,
			&i.SetorID,
			&i.SolicitanteID,
			&i.PreventivaID,
			&i.Status,
			&i.Origem,
			&i.Descricao,
			&i.MotivoRejeicao,
			&i.RejeitadoPorID,
			&i.RejeitadaEm,
			&i.CriadoEm,
			&i.MaquinaNome,
			&i.MaquinaCodigo,
			&i.MaquinaFotoChave,
			&i.SetorNome,
			&i.LojaID,
			&i.LojaNome,
			&i.SolicitanteNome,
			&i.RejeitadoPorNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSolicitacoesDoSolicitante = `-- name: ListarSolicitacoesDoSolicitante :many
SELECT
    s.id, s.tenant_id, s.tipo, s.maquina_id, s.item_descricao, s.setor_id, s.solicitante_id, s.preventiva_id, s.status, s.origem, s.descricao, s.motivo_rejeicao, s.rejeitado_por_id, s.rejeitada_em, s.criado_em,
    m.nome AS maquina_nome,
    m.numero_patrimonio AS maquina_codigo,
    m.foto_chave AS maquina_foto_chave,
    sc.nome AS setor_nome,
    sc.loja_id,
    l.nome AS loja_nome,
    sol.nome AS solicitante_nome,
    rej.nome AS rejeitado_por_nome
FROM solicitacao_os s
JOIN setor sc ON sc.tenant_id = s.tenant_id AND sc.id = s.setor_id
JOIN loja  l  ON l.tenant_id = sc.tenant_id AND l.id = sc.loja_id
LEFT JOIN maquina m   ON m.tenant_id = s.tenant_id AND m.id = s.maquina_id
LEFT JOIN usuario sol ON sol.tenant_id = s.tenant_id AND sol.id = s.solicitante_id
LEFT JOIN usuario rej ON rej.tenant_id = s.tenant_id AND rej.id = s.rejeitado_por_id
WHERE s.tenant_id = $1
  AND s.solicitante_id = $2
  AND ($3::status_solicitacao IS NULL OR s.status = $3)
  AND (
    $4::text IS NULL
    OR s.descricao ILIKE '%' || $4 || '%'
    OR m.nome ILIKE '%' || $4 || '%'
    OR s.item_descricao ILIKE '%' || $4 || '%'
  )
ORDER BY s.criado_em DESC
LIMIT $6 OFFSET $5
`

type ListarSolicitacoesDoSolicitanteParams struct {
	TenantID      int64
	SolicitanteID *int64
	Status        *StatusSolicitacao
	Busca         *string
	Deslocamento  int32
	Limite        int32
}

type ListarSolicitacoesDoSolicitanteRow struct {
	ID               int64
	TenantID         int64
	Tipo             TipoSolicitacao
	MaquinaID        *int64
	ItemDescricao    *string
	SetorID          int64
	SolicitanteID    *int64
	PreventivaID     *int64
	Status           StatusSolicitacao
	Origem           OrigemSolicitacao
	Descricao        string
	MotivoRejeicao   *string
	RejeitadoPorID   *int64
	RejeitadaEm      pgtype.Timestamptz
	CriadoEm         pgtype.Timestamptz
	MaquinaNome      *string
	MaquinaCodigo    *string
	MaquinaFotoChave *string
	SetorNome        string
	LojaID           int64
	LojaNome         string
	SolicitanteNome  *string
	RejeitadoPorNome *string
}

// GET /solicitacoes/minhas -- restrita ao próprio solicitante (nunca escopo:
// é a lista pessoal, não a fila do gestor), paginada por LIMIT/OFFSET porque
// model.RespostaPaginada exige os dois números (ContarSolicitacoesDoSolicitante
// abaixo, mesmo WHERE, mesmo motivo de ContarUsuarios repetir o de
// ListarUsuarios -- divergir dá total que não bate com a página).
func (q *Queries) ListarSolicitacoesDoSolicitante(ctx context.Context, arg ListarSolicitacoesDoSolicitanteParams) ([]ListarSolicitacoesDoSolicitanteRow, error) {
	rows, err := q.db.Query(ctx, listarSolicitacoesDoSolicitante,
		arg.TenantID,
		arg.SolicitanteID,
		arg.Status,
		arg.Busca,
		arg.Deslocamento,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarSolicitacoesDoSolicitanteRow
	for rows.Next() {
		var i ListarSolicitacoesDoSolicitanteRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Tipo,
			&i.MaquinaID,
			&i.ItemDescricao,
			&i.SetorID,
			&i.SolicitanteID,
			&i.PreventivaID,
			&i.Status,
			&i.Origem,
			&i.Descricao,
			&i.MotivoRejeicao,
			&i.RejeitadoPorID,
			&i.RejeitadaEm,
			&i.CriadoEm,
			&i.MaquinaNome,
			&i.MaquinaCodigo,
			&i.MaquinaFotoChave,
			&i.SetorNome,
			&i.LojaID,
			&i.LojaNome,
			&i.SolicitanteNome,
			&i.RejeitadoPorNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarSolicitacaoConvertida = `-- name: MarcarSolicitacaoConvertida :execrows
UPDATE solicitacao_os
SET status = 'Convertida'
WHERE id = $1 AND tenant_id = $2 AND status = 'Pendente'
`

type MarcarSolicitacaoConvertidaParams struct {
	ID       int64
	TenantID int64
}

// `AND status = 'Pendente'` no WHERE, não só no id: sem isso, abrir OS duas
// vezes seguidas passaria a segunda também (uq_os_solicitacao pegaria no
// INSERT de ordem_servico, mas tarde -- é melhor a solicitação já recusar
// antes de gastar o INSERT). 0 linhas afetadas é como o service sabe que não
// era Pendente e devolve ErrConflitoIntegridade, sem tentar o INSERT da OS.
func (q *Queries) MarcarSolicitacaoConvertida(ctx context.Context, arg MarcarSolicitacaoConvertidaParams) (int64, error) {
	result, err := q.db.Exec(ctx, marcarSolicitacaoConvertida, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const obterAnexosDaSolicitacao = `-- name: ObterAnexosDaSolicitacao :many
SELECT id, solicitacao_id, tipo, chave, mime_type, tamanho_bytes, criado_em FROM solicitacao_anexo WHERE solicitacao_id = $1 ORDER BY id
`

func (q *Queries) ObterAnexosDaSolicitacao(ctx context.Context, solicitacaoID int64) ([]SolicitacaoAnexo, error) {
	rows, err := q.db.Query(ctx, obterAnexosDaSolicitacao, solicitacaoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SolicitacaoAnexo
	for rows.Next() {
		var i SolicitacaoAnexo
		if err := rows.Scan(
			&i.ID,
			&i.SolicitacaoID,
			&i.Tipo,
			&i.Chave,
			&i.MimeType,
			&i.TamanhoBytes,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterAnexosDasSolicitacoes = `-- name: ObterAnexosDasSolicitacoes :many
SELECT id, solicitacao_id, tipo, chave, mime_type, tamanho_bytes, criado_em FROM solicitacao_anexo
WHERE solicitacao_id = ANY($1::bigint[])
ORDER BY solicitacao_id, id
`

// Plural de propósito, mesmo motivo de ObterImpactosDasSolicitacoes: quem
// monta uma página de solicitações busca os anexos de todas numa ida só.
func (q *Queries) ObterAnexosDasSolicitacoes(ctx context.Context, solicitacaoIds []int64) ([]SolicitacaoAnexo, error) {
	rows, err := q.db.Query(ctx, obterAnexosDasSolicitacoes, solicitacaoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SolicitacaoAnexo
	for rows.Next() {
		var i SolicitacaoAnexo
		if err := rows.Scan(
			&i.ID,
			&i.SolicitacaoID,
			&i.Tipo,
			&i.Chave,
			&i.MimeType,
			&i.TamanhoBytes,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterImpactosDaSolicitacao = `-- name: ObterImpactosDaSolicitacao :many
SELECT marcador FROM solicitacao_impacto WHERE solicitacao_id = $1
`

// Filhos de uma solicitação só, usada por ObterSolicitacaoPorID (GET /:id, e
// pela criação, que relê por ali dentro da mesma transação).
func (q *Queries) ObterImpactosDaSolicitacao(ctx context.Context, solicitacaoID int64) ([]MarcadorImpacto, error) {
	rows, err := q.db.Query(ctx, obterImpactosDaSolicitacao, solicitacaoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarcadorImpacto
	for rows.Next() {
		var marcador MarcadorImpacto
		if err := rows.Scan(&marcador); err != nil {
			return nil, err
		}
		items = append(items, marcador)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterImpactosDasSolicitacoes = `-- name: ObterImpactosDasSolicitacoes :many
SELECT solicitacao_id, marcador
FROM solicitacao_impacto
WHERE solicitacao_id = ANY($1::bigint[])
ORDER BY solicitacao_id
`

// Mesma forma da anterior, para uma página inteira numa ida só ao banco --
// mesmo padrão de ObterEscoposSessaoPorUsuarios (usuario_escopo.sql): quem
// lista usa a plural para não fazer N+1, uma query por solicitação da página.
func (q *Queries) ObterImpactosDasSolicitacoes(ctx context.Context, solicitacaoIds []int64) ([]SolicitacaoImpacto, error) {
	rows, err := q.db.Query(ctx, obterImpactosDasSolicitacoes, solicitacaoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SolicitacaoImpacto
	for rows.Next() {
		var i SolicitacaoImpacto
		if err := rows.Scan(&i.SolicitacaoID, &i.Marcador); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterResumoSolicitacoes = `-- name: ObterResumoSolicitacoes :one
SELECT
    count(*) FILTER (WHERE s.status = 'Pendente' OR o.status = 'Aberta')::bigint AS abertas,
    count(*) FILTER (WHERE o.status IN ('Em Andamento', 'Pausada'))::bigint AS em_andamento,
    count(*) FILTER (WHERE o.status = 'Concluída')::bigint AS concluidas
FROM solicitacao_os s
LEFT JOIN ordem_servico o ON o.solicitacao_id = s.id
WHERE s.tenant_id = $1 AND s.solicitante_id = $2
`

type ObterResumoSolicitacoesParams struct {
	TenantID      int64
	SolicitanteID *int64
}

type ObterResumoSolicitacoesRow struct {
	Abertas     int64
	EmAndamento int64
	Concluidas  int64
}

// GET /solicitacoes/resumo -- os três contadores da Home do Solicitante.
// `abertas`/`emAndamento`/`concluidas` não são estados de solicitacao_os
// (que só tem Pendente/Convertida/Rejeitada): são o status da OrdemServico
// que ela virou, por isso o LEFT JOIN com ordem_servico. Uma solicitação
// Pendente conta como "aberta" (ainda não foi nem avaliada); Rejeitada não
// entra em nenhum balde, de propósito -- não é trabalho aberto nem
// concluído, e a tela nem mostra essa categoria.
//
// count(*) FILTER (WHERE ...) e não três subqueries: uma passada só pela
// tabela, sem repetir o FROM/WHERE três vezes.
func (q *Queries) ObterResumoSolicitacoes(ctx context.Context, arg ObterResumoSolicitacoesParams) (ObterResumoSolicitacoesRow, error) {
	row := q.db.QueryRow(ctx, obterResumoSolicitacoes, arg.TenantID, arg.SolicitanteID)
	var i ObterResumoSolicitacoesRow
	err := row.Scan(&i.Abertas, &i.EmAndamento, &i.Concluidas)
	return i, err
}

const obterSolicitacaoPorID = `-- name: ObterSolicitacaoPorID :one
SELECT
    s.id, s.tenant_id, s.tipo, s.maquina_id, s.item_descricao, s.setor_id, s.solicitante_id, s.preventiva_id, s.status, s.origem, s.descricao, s.motivo_rejeicao, s.rejeitado_por_id, s.rejeitada_em, s.criado_em,
    m.nome AS maquina_nome,
    m.numero_patrimonio AS maquina_codigo,
    m.foto_chave AS maquina_foto_chave,
    sc.nome AS setor_nome,
    sc.loja_id,
    l.nome AS loja_nome,
    sol.nome AS solicitante_nome,
    rej.nome AS rejeitado_por_nome
FROM solicitacao_os s
JOIN setor sc ON sc.tenant_id = s.tenant_id AND sc.id = s.setor_id
JOIN loja  l  ON l.tenant_id = sc.tenant_id AND l.id = sc.loja_id
LEFT JOIN maquina m   ON m.tenant_id = s.tenant_id AND m.id = s.maquina_id
LEFT JOIN usuario sol ON sol.tenant_id = s.tenant_id AND sol.id = s.solicitante_id
LEFT JOIN usuario rej ON rej.tenant_id = s.tenant_id AND rej.id = s.rejeitado_por_id
WHERE s.id = $1 AND s.tenant_id = $2
  AND (
    $3::bigint IS NULL
    OR EXISTS (
      SELECT 1
      FROM usuario_escopo ue
      LEFT JOIN usuario_escopo_setor ues ON ues.escopo_id = ue.id
      WHERE ue.usuario_id = $3
        AND ue.loja_id = sc.loja_id
        AND (ue.acesso_total_setores OR ues.setor_id = s.setor_id)
    )
  )
`

type ObterSolicitacaoPorIDParams struct {
	ID              int64
	TenantID        int64
	EscopoUsuarioID *int64
}

type ObterSolicitacaoPorIDRow struct {
	ID               int64
	TenantID         int64
	Tipo             TipoSolicitacao
	MaquinaID        *int64
	ItemDescricao    *string
	SetorID          int64
	SolicitanteID    *int64
	PreventivaID     *int64
	Status           StatusSolicitacao
	Origem           OrigemSolicitacao
	Descricao        string
	MotivoRejeicao   *string
	RejeitadoPorID   *int64
	RejeitadaEm      pgtype.Timestamptz
	CriadoEm         pgtype.Timestamptz
	MaquinaNome      *string
	MaquinaCodigo    *string
	MaquinaFotoChave *string
	SetorNome        string
	LojaID           int64
	LojaNome         string
	SolicitanteNome  *string
	RejeitadoPorNome *string
}

// Traz os denormalizados que SolicitacaoOS do front exige: maquinaNome/
// maquinaCodigo/maquinaFotoUrl (reparo não tem máquina -- os três vêm NULL
// via LEFT JOIN), setorNome/lojaId/lojaNome (sempre presentes -- toda
// solicitação tem setor), solicitanteNome (NULL quando origem = 'preventiva')
// e rejeitadoPorNome (NULL enquanto não rejeitada).
//
// Impactos e anexos ficam de fora de propósito, em vez de um array_agg aqui
// dentro: mesmo padrão de usuário/escopo (ObterUsuarioPorID não traz o
// escopo -- quem busca é uma query própria). Evita GROUP BY sobre `s.*` e
// mantém uma única forma de buscar cada filho, reaproveitada tanto para uma
// solicitação (aqui) quanto para uma página inteira delas (as `...Das...`
// plurais abaixo).
//
// JOINs de setor/loja são INNER (NOT NULL, FK garante); máquina, solicitante
// e rejeitado_por são LEFT (todos nullable no schema).
//
// escopo_usuario_id é opcional, mesmo `escopoDe(usuarioId, perfil)` de
// ListarSolicitacoes -- e todo chamador manda ele, sempre: GET
// /solicitacoes/:id (aberto a qualquer perfil) para não deixar um
// Solicitante enumerar id e ler foto/descrição de outro setor, e
// AbrirOS/Rejeitar (só gestor/administrador na rota) para o Gestor não agir
// em solicitação de loja que ele não atende. NULL só quando `escopoDe`
// devolve NULL, ou seja, para administrador -- ele não tem escopo, a
// ausência É o acesso total. Fora do escopo cai em pgx.ErrNoRows como se o
// id não existisse -- 404, nunca 403, mesmo critério de "filtro do cliente
// estreita, nunca amplia".
func (q *Queries) ObterSolicitacaoPorID(ctx context.Context, arg ObterSolicitacaoPorIDParams) (ObterSolicitacaoPorIDRow, error) {
	row := q.db.QueryRow(ctx, obterSolicitacaoPorID, arg.ID, arg.TenantID, arg.EscopoUsuarioID)
	var i ObterSolicitacaoPorIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Tipo,
		&i.MaquinaID,
		&i.ItemDescricao,
		&i.SetorID,
		&i.SolicitanteID,
		&i.PreventivaID,
		&i.Status,
		&i.Origem,
		&i.Descricao,
		&i.MotivoRejeicao,
		&i.RejeitadoPorID,
		&i.RejeitadaEm,
		&i.CriadoEm,
		&i.MaquinaNome,
		&i.MaquinaCodigo,
		&i.MaquinaFotoChave,
		&i.SetorNome,
		&i.LojaID,
		&i.LojaNome,
		&i.SolicitanteNome,
		&i.RejeitadoPorNome,
	)
	return i, err
}

const rejeitarSolicitacao = `-- name: RejeitarSolicitacao :execrows
UPDATE solicitacao_os
SET status = 'Rejeitada',
    motivo_rejeicao = $1,
    rejeitado_por_id = $2,
    rejeitada_em = now()
WHERE id = $3 AND tenant_id = $4 AND status = 'Pendente'
`

type RejeitarSolicitacaoParams struct {
	MotivoRejeicao *string
	RejeitadoPorID *int64
	ID             int64
	TenantID       int64
}

// ck_rejeicao exige os três juntos (motivo, autor, instante) -- por isso
// entram juntos aqui, nunca um UPDATE incremental. Mesmo filtro
// `status = 'Pendente'` de MarcarSolicitacaoConvertida e pelo mesmo motivo:
// não rejeitar (nem re-rejeitar) o que já saiu do estado inicial.
func (q *Queries) RejeitarSolicitacao(ctx context.Context, arg RejeitarSolicitacaoParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejeitarSolicitacao,
		arg.MotivoRejeicao,
		arg.RejeitadoPorID,
		arg.ID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
