// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuario.sql

package repository

import (
	"context"
)

const atualizarSenhaUsuario = `-- name: AtualizarSenhaUsuario :exec
UPDATE usuario
SET senha_hash = $3
WHERE id = $1 AND tenant_id = $2
`

type AtualizarSenhaUsuarioParams struct {
	ID        int64
	TenantID  int64
	SenhaHash string
}

func (q *Queries) AtualizarSenhaUsuario(ctx context.Context, arg AtualizarSenhaUsuarioParams) error {
	_, err := q.db.Exec(ctx, atualizarSenhaUsuario, arg.ID, arg.TenantID, arg.SenhaHash)
	return err
}

const atualizarUsuario = `-- name: AtualizarUsuario :one
UPDATE usuario
SET perfil = $3,
    area_tecnico_id = $4,
    nome = $5,
    email = $6,
    telefone = $7
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, perfil, area_tecnico_id, nome, email, senha_hash, telefone, ativo, ultimo_acesso, criado_em
`

type AtualizarUsuarioParams struct {
	ID            int64
	TenantID      int64
	Perfil        PerfilUsuario
	AreaTecnicoID *int16
	Nome          string
	Email         string
	Telefone      *string
}

// Sem senha_hash -- troca de senha tem query própria (AtualizarSenhaUsuario),
// porque na edição ela é opcional (ver CadastrarUsuario: senha omitida mantém
// o hash atual).
func (q *Queries) AtualizarUsuario(ctx context.Context, arg AtualizarUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, atualizarUsuario,
		arg.ID,
		arg.TenantID,
		arg.Perfil,
		arg.AreaTecnicoID,
		arg.Nome,
		arg.Email,
		arg.Telefone,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Perfil,
		&i.AreaTecnicoID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Telefone,
		&i.Ativo,
		&i.UltimoAcesso,
		&i.CriadoEm,
	)
	return i, err
}

const contarUsuarios = `-- name: ContarUsuarios :one
SELECT count(*) FROM usuario
WHERE tenant_id = $1
  AND ativo
  AND ($2::perfil_usuario IS NULL OR perfil = $2)
  AND (
    $3::text IS NULL
    OR nome ILIKE '%' || $3 || '%'
    OR email ILIKE '%' || $3 || '%'
  )
  AND (
    $4::bigint IS NULL
    OR EXISTS (
      SELECT 1 FROM usuario_escopo ue
      WHERE ue.usuario_id = usuario.id AND ue.loja_id = $4
    )
  )
`

type ContarUsuariosParams struct {
	TenantID int64
	Perfil   *PerfilUsuario
	Busca    *string
	LojaID   *int64
}

func (q *Queries) ContarUsuarios(ctx context.Context, arg ContarUsuariosParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarUsuarios,
		arg.TenantID,
		arg.Perfil,
		arg.Busca,
		arg.LojaID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarUsuario = `-- name: CriarUsuario :one

INSERT INTO usuario (tenant_id, perfil, area_tecnico_id, nome, email, senha_hash, telefone)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, perfil, area_tecnico_id, nome, email, senha_hash, telefone, ativo, ultimo_acesso, criado_em
`

type CriarUsuarioParams struct {
	TenantID      int64
	Perfil        PerfilUsuario
	AreaTecnicoID *int16
	Nome          string
	Email         string
	SenhaHash     string
	Telefone      *string
}

// Exclusão é sempre soft delete (ativo = false) -- ver "Soft delete" em
// docs/modelagem-banco-dados.md: perde-se o cadastro, não o histórico de OS
// vinculado ao usuário (solicitante/técnico/gestor).
func (q *Queries) CriarUsuario(ctx context.Context, arg CriarUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, criarUsuario,
		arg.TenantID,
		arg.Perfil,
		arg.AreaTecnicoID,
		arg.Nome,
		arg.Email,
		arg.SenhaHash,
		arg.Telefone,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Perfil,
		&i.AreaTecnicoID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Telefone,
		&i.Ativo,
		&i.UltimoAcesso,
		&i.CriadoEm,
	)
	return i, err
}

const desativarUsuario = `-- name: DesativarUsuario :execrows
UPDATE usuario
SET ativo = false
WHERE id = $1 AND tenant_id = $2
`

type DesativarUsuarioParams struct {
	ID       int64
	TenantID int64
}

// :execrows e não :exec -- sem a contagem de linhas, desativar um id que não
// existe (ou que é de outro tenant) responderia 200 igualzinho a desativar um
// de verdade. Já desativado conta 1 mesmo assim: o UPDATE casa a linha.
func (q *Queries) DesativarUsuario(ctx context.Context, arg DesativarUsuarioParams) (int64, error) {
	result, err := q.db.Exec(ctx, desativarUsuario, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarUsuarios = `-- name: ListarUsuarios :many
SELECT id, tenant_id, perfil, area_tecnico_id, nome, email, senha_hash, telefone, ativo, ultimo_acesso, criado_em FROM usuario
WHERE tenant_id = $1
  AND ativo
  AND ($4::perfil_usuario IS NULL OR perfil = $4)
  AND (
    $5::text IS NULL
    OR nome ILIKE '%' || $5 || '%'
    OR email ILIKE '%' || $5 || '%'
  )
  AND (
    $6::bigint IS NULL
    OR EXISTS (
      SELECT 1 FROM usuario_escopo ue
      WHERE ue.usuario_id = usuario.id AND ue.loja_id = $6
    )
  )
ORDER BY nome
LIMIT $2 OFFSET $3
`

type ListarUsuariosParams struct {
	TenantID int64
	Limit    int32
	Offset   int32
	Perfil   *PerfilUsuario
	Busca    *string
	LojaID   *int64
}

// Filtros combináveis: perfil, busca (nome/email) e loja_id são opcionais --
// passe NULL para não filtrar por eles. Paginação por LIMIT/OFFSET, contagem
// total em ContarUsuarios (RespostaPaginada exige os dois).
//
// loja_id filtra pelo escopo de acesso (usuario_escopo), com EXISTS e não
// JOIN: usuário com N escopos apareceria N vezes e estouraria o LIMIT com
// repetição. Administrador não tem escopo nenhum (a ausência É o acesso
// total, 3.8), então some de qualquer listagem filtrada por loja -- que é o
// certo: ele não pertence a loja alguma. ContarUsuarios repete o mesmo WHERE
// de propósito; divergir entre as duas dá total que não bate com a página.
func (q *Queries) ListarUsuarios(ctx context.Context, arg ListarUsuariosParams) ([]Usuario, error) {
	rows, err := q.db.Query(ctx, listarUsuarios,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Perfil,
		arg.Busca,
		arg.LojaID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Perfil,
			&i.AreaTecnicoID,
			&i.Nome,
			&i.Email,
			&i.SenhaHash,
			&i.Telefone,
			&i.Ativo,
			&i.UltimoAcesso,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterUsuarioPorEmail = `-- name: ObterUsuarioPorEmail :one
SELECT id, tenant_id, perfil, area_tecnico_id, nome, email, senha_hash, telefone, ativo, ultimo_acesso, criado_em FROM usuario
WHERE tenant_id = $1 AND email = $2 AND ativo
`

type ObterUsuarioPorEmailParams struct {
	TenantID int64
	Email    string
}

// Usado no login: email é citext (case-insensitive) e único por tenant.
func (q *Queries) ObterUsuarioPorEmail(ctx context.Context, arg ObterUsuarioPorEmailParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, obterUsuarioPorEmail, arg.TenantID, arg.Email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Perfil,
		&i.AreaTecnicoID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Telefone,
		&i.Ativo,
		&i.UltimoAcesso,
		&i.CriadoEm,
	)
	return i, err
}

const obterUsuarioPorID = `-- name: ObterUsuarioPorID :one
SELECT id, tenant_id, perfil, area_tecnico_id, nome, email, senha_hash, telefone, ativo, ultimo_acesso, criado_em FROM usuario
WHERE id = $1 AND tenant_id = $2
`

type ObterUsuarioPorIDParams struct {
	ID       int64
	TenantID int64
}

func (q *Queries) ObterUsuarioPorID(ctx context.Context, arg ObterUsuarioPorIDParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, obterUsuarioPorID, arg.ID, arg.TenantID)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Perfil,
		&i.AreaTecnicoID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Telefone,
		&i.Ativo,
		&i.UltimoAcesso,
		&i.CriadoEm,
	)
	return i, err
}

const registrarUltimoAcesso = `-- name: RegistrarUltimoAcesso :exec
UPDATE usuario
SET ultimo_acesso = now()
WHERE id = $1 AND tenant_id = $2
`

type RegistrarUltimoAcessoParams struct {
	ID       int64
	TenantID int64
}

func (q *Queries) RegistrarUltimoAcesso(ctx context.Context, arg RegistrarUltimoAcessoParams) error {
	_, err := q.db.Exec(ctx, registrarUltimoAcesso, arg.ID, arg.TenantID)
	return err
}
