// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuario.sql

package repository

import (
	"context"
)

const atualizarSenhaUsuario = `-- name: AtualizarSenhaUsuario :exec
UPDATE usuario
SET senha_hash = $3
WHERE id = $1 AND tenant_id = $2
`

type AtualizarSenhaUsuarioParams struct {
	ID        int64
	TenantID  int64
	SenhaHash string
}

func (q *Queries) AtualizarSenhaUsuario(ctx context.Context, arg AtualizarSenhaUsuarioParams) error {
	_, err := q.db.Exec(ctx, atualizarSenhaUsuario, arg.ID, arg.TenantID, arg.SenhaHash)
	return err
}

const atualizarUsuario = `-- name: AtualizarUsuario :one
UPDATE usuario
SET perfil = $3,
    area_tecnico_id = $4,
    nome = $5,
    email = $6,
    telefone = $7
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, perfil, area_tecnico_id, nome, email, senha_hash, telefone, ativo, ultimo_acesso, criado_em
`

type AtualizarUsuarioParams struct {
	ID            int64
	TenantID      int64
	Perfil        PerfilUsuario
	AreaTecnicoID *int16
	Nome          string
	Email         string
	Telefone      *string
}

// Sem senha_hash -- troca de senha tem query própria (AtualizarSenhaUsuario),
// porque na edição ela é opcional (ver CadastrarUsuario: senha omitida mantém
// o hash atual).
func (q *Queries) AtualizarUsuario(ctx context.Context, arg AtualizarUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, atualizarUsuario,
		arg.ID,
		arg.TenantID,
		arg.Perfil,
		arg.AreaTecnicoID,
		arg.Nome,
		arg.Email,
		arg.Telefone,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Perfil,
		&i.AreaTecnicoID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Telefone,
		&i.Ativo,
		&i.UltimoAcesso,
		&i.CriadoEm,
	)
	return i, err
}

const contarUsuarios = `-- name: ContarUsuarios :one
SELECT count(*) FROM usuario
WHERE tenant_id = $1
  AND ativo
  AND ($2::perfil_usuario IS NULL OR perfil = $2)
  AND (
    $3::text IS NULL
    OR nome ILIKE '%' || $3 || '%'
    OR email ILIKE '%' || $3 || '%'
  )
  AND (
    $4::bigint IS NULL
    OR EXISTS (
      SELECT 1 FROM usuario_escopo ue
      WHERE ue.usuario_id = usuario.id AND ue.loja_id = $4
    )
  )
`

type ContarUsuariosParams struct {
	TenantID int64
	Perfil   *PerfilUsuario
	Busca    *string
	LojaID   *int64
}

func (q *Queries) ContarUsuarios(ctx context.Context, arg ContarUsuariosParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarUsuarios,
		arg.TenantID,
		arg.Perfil,
		arg.Busca,
		arg.LojaID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarUsuario = `-- name: CriarUsuario :one

INSERT INTO usuario (tenant_id, perfil, area_tecnico_id, nome, email, senha_hash, telefone)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, perfil, area_tecnico_id, nome, email, senha_hash, telefone, ativo, ultimo_acesso, criado_em
`

type CriarUsuarioParams struct {
	TenantID      int64
	Perfil        PerfilUsuario
	AreaTecnicoID *int16
	Nome          string
	Email         string
	SenhaHash     string
	Telefone      *string
}

// Exclusão é sempre soft delete (ativo = false) -- ver "Soft delete" em
// docs/modelagem-banco-dados.md: perde-se o cadastro, não o histórico de OS
// vinculado ao usuário (solicitante/técnico/gestor).
func (q *Queries) CriarUsuario(ctx context.Context, arg CriarUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, criarUsuario,
		arg.TenantID,
		arg.Perfil,
		arg.AreaTecnicoID,
		arg.Nome,
		arg.Email,
		arg.SenhaHash,
		arg.Telefone,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Perfil,
		&i.AreaTecnicoID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Telefone,
		&i.Ativo,
		&i.UltimoAcesso,
		&i.CriadoEm,
	)
	return i, err
}

const desativarUsuario = `-- name: DesativarUsuario :execrows
UPDATE usuario
SET ativo = false
WHERE id = $1 AND tenant_id = $2
`

type DesativarUsuarioParams struct {
	ID       int64
	TenantID int64
}

// :execrows e não :exec -- sem a contagem de linhas, desativar um id que não
// existe (ou que é de outro tenant) responderia 200 igualzinho a desativar um
// de verdade. Já desativado conta 1 mesmo assim: o UPDATE casa a linha.
func (q *Queries) DesativarUsuario(ctx context.Context, arg DesativarUsuarioParams) (int64, error) {
	result, err := q.db.Exec(ctx, desativarUsuario, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarTecnicos = `-- name: ListarTecnicos :many
SELECT
    u.id,
    u.nome,
    u.email,
    u.telefone,
    a.nome AS area,
    COALESCE(
        array_agg(ue.loja_id) FILTER (WHERE ue.loja_id IS NOT NULL),
        '{}'
    )::bigint[] AS lojas_ids
FROM usuario u
JOIN area_tecnico a
  ON a.tenant_id = u.tenant_id AND a.id = u.area_tecnico_id
LEFT JOIN usuario_escopo ue
  ON ue.usuario_id = u.id
WHERE u.tenant_id = $1
  AND u.perfil = 'tecnico'
  AND u.ativo
  AND (
    ($2::bigint IS NULL AND $3::bigint IS NULL)
    OR EXISTS (
      SELECT 1
      FROM usuario_escopo t
      WHERE t.usuario_id = u.id
        AND ($2::bigint IS NULL OR t.loja_id = $2)
        AND (
          $3::bigint IS NULL
          OR EXISTS (
            SELECT 1 FROM usuario_escopo c
            WHERE c.usuario_id = $3
              AND c.loja_id = t.loja_id
          )
        )
    )
  )
GROUP BY u.id, u.nome, u.email, u.telefone, a.nome
ORDER BY u.nome
`

type ListarTecnicosParams struct {
	TenantID        int64
	LojaID          *int64
	EscopoUsuarioID *int64
}

type ListarTecnicosRow struct {
	ID       int64
	Nome     string
	Email    string
	Telefone *string
	Area     string
	LojasIds []int64
}

// GET /tecnicos -- projeção somente-leitura sobre `usuario`, não tabela
// própria: técnico é usuário com perfil 'tecnico'. Existe separada de
// ListarUsuarios por três motivos, e o primeiro é o que obriga:
//
//  1. RBAC. /usuarios inteiro é do administrador, e quem precisa desta lista é
//     o GESTOR, no select de "Técnico Responsável" do ModalAbrirOrdemServico --
//     ele levaria 403 na outra rota.
//  2. Forma. O tipo Tecnico do front pede `area` como NOME ("Refrigeração") e
//     `lojasIds`; ListarUsuarios não junta area_tecnico e é paginada, enquanto
//     o select quer array simples.
//  3. Escrita continua em /usuarios (mesma tabela) -- duas superfícies de
//     escrita deixariam o mesmo e-mail entrar duas vezes.
//
// O JOIN com area_tecnico é INNER porque ck_usuario_area_tecnico garante
// area_tecnico_id NOT NULL exatamente para o perfil 'tecnico'.
//
// lojas_ids sai de array_agg com FILTER + COALESCE: técnico sem escopo nenhum
// (não deve existir -- o cadastro exige loja) devolveria {NULL} sem o filtro, e
// NULL sem o COALESCE. O cast final é o que faz o sqlc gerar []int64 em vez de
// interface{} -- mesma armadilha do `vencida` em preventiva.sql.
//
// Os dois filtros são EXISTS e não JOIN, mesmo motivo de ListarUsuarios: com
// JOIN o técnico apareceria uma vez por escopo que casa.
//
//	loja_id           -- a loja da solicitação, mandada pelo modal do gestor.
//	escopo_usuario_id -- quem chama (NULL = administrador, não filtra). Sem
//	                     isto um gestor lista nome e e-mail dos técnicos de
//	                     lojas que ele não enxerga.
//
// ⚠️ Os dois filtros vivem no MESMO EXISTS, sobre a mesma linha de
// usuario_escopo, e isso é o ponto: separados, eles pediriam "atende a loja X"
// E "divide alguma loja comigo" -- que não é a mesma coisa. Um gestor da Loja A
// pedindo ?lojaId=B receberia o técnico que atende A e B, porque cada condição
// passava por uma loja diferente. Tem que ser a mesma loja ligando os dois.
// (Foi assim que a primeira versão saiu; o teste de integração pegou.)
func (q *Queries) ListarTecnicos(ctx context.Context, arg ListarTecnicosParams) ([]ListarTecnicosRow, error) {
	rows, err := q.db.Query(ctx, listarTecnicos, arg.TenantID, arg.LojaID, arg.EscopoUsuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarTecnicosRow
	for rows.Next() {
		var i ListarTecnicosRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Email,
			&i.Telefone,
			&i.Area,
			&i.LojasIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarUsuarios = `-- name: ListarUsuarios :many
SELECT id, tenant_id, perfil, area_tecnico_id, nome, email, senha_hash, telefone, ativo, ultimo_acesso, criado_em FROM usuario
WHERE tenant_id = $1
  AND ativo
  AND ($4::perfil_usuario IS NULL OR perfil = $4)
  AND (
    $5::text IS NULL
    OR nome ILIKE '%' || $5 || '%'
    OR email ILIKE '%' || $5 || '%'
  )
  AND (
    $6::bigint IS NULL
    OR EXISTS (
      SELECT 1 FROM usuario_escopo ue
      WHERE ue.usuario_id = usuario.id AND ue.loja_id = $6
    )
  )
ORDER BY nome
LIMIT $2 OFFSET $3
`

type ListarUsuariosParams struct {
	TenantID int64
	Limit    int32
	Offset   int32
	Perfil   *PerfilUsuario
	Busca    *string
	LojaID   *int64
}

// Filtros combináveis: perfil, busca (nome/email) e loja_id são opcionais --
// passe NULL para não filtrar por eles. Paginação por LIMIT/OFFSET, contagem
// total em ContarUsuarios (RespostaPaginada exige os dois).
//
// loja_id filtra pelo escopo de acesso (usuario_escopo), com EXISTS e não
// JOIN: usuário com N escopos apareceria N vezes e estouraria o LIMIT com
// repetição. Administrador não tem escopo nenhum (a ausência É o acesso
// total, 3.8), então some de qualquer listagem filtrada por loja -- que é o
// certo: ele não pertence a loja alguma. ContarUsuarios repete o mesmo WHERE
// de propósito; divergir entre as duas dá total que não bate com a página.
func (q *Queries) ListarUsuarios(ctx context.Context, arg ListarUsuariosParams) ([]Usuario, error) {
	rows, err := q.db.Query(ctx, listarUsuarios,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Perfil,
		arg.Busca,
		arg.LojaID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Perfil,
			&i.AreaTecnicoID,
			&i.Nome,
			&i.Email,
			&i.SenhaHash,
			&i.Telefone,
			&i.Ativo,
			&i.UltimoAcesso,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterGestoresDoSetor = `-- name: ObterGestoresDoSetor :many
SELECT u.id, u.nome, u.telefone
FROM usuario u
JOIN setor s ON s.tenant_id = u.tenant_id AND s.id = $1
WHERE u.tenant_id = $2
  AND u.perfil = 'gestor'
  AND u.ativo
  AND u.telefone IS NOT NULL
  AND EXISTS (
    SELECT 1
    FROM usuario_escopo ue
    LEFT JOIN usuario_escopo_setor ues ON ues.escopo_id = ue.id
    WHERE ue.usuario_id = u.id
      AND ue.loja_id = s.loja_id
      AND (ue.acesso_total_setores OR ues.setor_id = $1)
  )
ORDER BY u.nome
`

type ObterGestoresDoSetorParams struct {
	SetorID  int64
	TenantID int64
}

type ObterGestoresDoSetorRow struct {
	ID       int64
	Nome     string
	Telefone *string
}

// Quem recebe a notificação de WhatsApp quando uma Solicitação nasce naquele
// setor (ver CLAUDE.md, "Notificação de solicitação por WhatsApp"): todo
// gestor cujo escopo alcança o setor, mesmo critério de "alcança" do EXISTS
// em ListarSolicitacoes/ListarMaquinas -- a loja bate E, dentro dela, acesso
// total OU o setor específico marcado.
//
// Administrador não entra: não tem linha em usuario_escopo
// (trg_usuario_escopo_nao_admin recusa) -- a ausência de escopo É o acesso
// total ao tenant, não dá pra "alcançar um setor" a partir do vazio. A
// notificação de solicitação é só pro Gestor por ora (ver CLAUDE.md);
// Técnico entra quando a fase 2 existir, com sua própria query.
//
// Sem telefone cadastrado, o gestor não aparece -- não é erro, é degrade
// silencioso: quem chama (NotificacaoService) não teria pra onde mandar de
// qualquer forma. Ativo também filtra: gestor desativado não deve saber de
// solicitação nova.
//
// EXISTS e não JOIN, mesmo motivo de ListarUsuarios/ListarTecnicos: com JOIN
// o gestor apareceria uma vez por linha de usuario_escopo_setor que casasse
// (e com acesso_total_setores, a linha de usuario_escopo não tem setor
// nenhum atrelado -- LEFT JOIN duplicaria por engano se fosse feito fora do
// EXISTS).
func (q *Queries) ObterGestoresDoSetor(ctx context.Context, arg ObterGestoresDoSetorParams) ([]ObterGestoresDoSetorRow, error) {
	rows, err := q.db.Query(ctx, obterGestoresDoSetor, arg.SetorID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObterGestoresDoSetorRow
	for rows.Next() {
		var i ObterGestoresDoSetorRow
		if err := rows.Scan(&i.ID, &i.Nome, &i.Telefone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterUsuarioPorEmail = `-- name: ObterUsuarioPorEmail :one
SELECT id, tenant_id, perfil, area_tecnico_id, nome, email, senha_hash, telefone, ativo, ultimo_acesso, criado_em FROM usuario
WHERE tenant_id = $1 AND email = $2 AND ativo
`

type ObterUsuarioPorEmailParams struct {
	TenantID int64
	Email    string
}

// Usado no login: email é citext (case-insensitive) e único por tenant.
func (q *Queries) ObterUsuarioPorEmail(ctx context.Context, arg ObterUsuarioPorEmailParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, obterUsuarioPorEmail, arg.TenantID, arg.Email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Perfil,
		&i.AreaTecnicoID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Telefone,
		&i.Ativo,
		&i.UltimoAcesso,
		&i.CriadoEm,
	)
	return i, err
}

const obterUsuarioPorID = `-- name: ObterUsuarioPorID :one
SELECT id, tenant_id, perfil, area_tecnico_id, nome, email, senha_hash, telefone, ativo, ultimo_acesso, criado_em FROM usuario
WHERE id = $1 AND tenant_id = $2
`

type ObterUsuarioPorIDParams struct {
	ID       int64
	TenantID int64
}

func (q *Queries) ObterUsuarioPorID(ctx context.Context, arg ObterUsuarioPorIDParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, obterUsuarioPorID, arg.ID, arg.TenantID)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Perfil,
		&i.AreaTecnicoID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Telefone,
		&i.Ativo,
		&i.UltimoAcesso,
		&i.CriadoEm,
	)
	return i, err
}

const registrarUltimoAcesso = `-- name: RegistrarUltimoAcesso :exec
UPDATE usuario
SET ultimo_acesso = now()
WHERE id = $1 AND tenant_id = $2
`

type RegistrarUltimoAcessoParams struct {
	ID       int64
	TenantID int64
}

func (q *Queries) RegistrarUltimoAcesso(ctx context.Context, arg RegistrarUltimoAcessoParams) error {
	_, err := q.db.Exec(ctx, registrarUltimoAcesso, arg.ID, arg.TenantID)
	return err
}
