// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuario_escopo.sql

package repository

import (
	"context"
)

const criarEscopo = `-- name: CriarEscopo :one

INSERT INTO usuario_escopo (usuario_id, loja_id, acesso_total_setores)
VALUES ($1, $2, $3)
RETURNING id, usuario_id, loja_id, acesso_total_setores, criado_em
`

type CriarEscopoParams struct {
	UsuarioID          int64
	LojaID             int64
	AcessoTotalSetores bool
}

// Escopo de acesso (loja + setor) dos 4 perfis -- ver "3.8 Escopo de acesso
// unificado" em docs/modelagem-banco-dados.md:
//
//	Solicitante: 1 escopo, acesso_total_setores = false, exatamente 1 setor.
//	Técnico:     N escopos, acesso_total_setores = true (sem linha de setor).
//	Gestor:      N escopos, cada um acesso_total OU uma lista de setores.
//	Administrador: nenhum escopo -- a ausência É o acesso total ao tenant.
//
// Editar substitui o conjunto inteiro (mesmo padrão de preventivas em
// CadastrarMaquina): o service apaga tudo do usuário e recria, numa
// transação -- não há UPDATE de escopo individual aqui de propósito.
func (q *Queries) CriarEscopo(ctx context.Context, arg CriarEscopoParams) (UsuarioEscopo, error) {
	row := q.db.QueryRow(ctx, criarEscopo, arg.UsuarioID, arg.LojaID, arg.AcessoTotalSetores)
	var i UsuarioEscopo
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.LojaID,
		&i.AcessoTotalSetores,
		&i.CriadoEm,
	)
	return i, err
}

const criarEscopoSetor = `-- name: CriarEscopoSetor :exec
INSERT INTO usuario_escopo_setor (escopo_id, setor_id)
VALUES ($1, $2)
`

type CriarEscopoSetorParams struct {
	EscopoID int64
	SetorID  int64
}

func (q *Queries) CriarEscopoSetor(ctx context.Context, arg CriarEscopoSetorParams) error {
	_, err := q.db.Exec(ctx, criarEscopoSetor, arg.EscopoID, arg.SetorID)
	return err
}

const deletarEscoposPorUsuario = `-- name: DeletarEscoposPorUsuario :exec
DELETE FROM usuario_escopo
WHERE usuario_id = $1
`

func (q *Queries) DeletarEscoposPorUsuario(ctx context.Context, usuarioID int64) error {
	_, err := q.db.Exec(ctx, deletarEscoposPorUsuario, usuarioID)
	return err
}

const deletarSetoresDosEscoposPorUsuario = `-- name: DeletarSetoresDosEscoposPorUsuario :exec
DELETE FROM usuario_escopo_setor
WHERE escopo_id IN (SELECT id FROM usuario_escopo WHERE usuario_id = $1)
`

// Roda antes de DeletarEscoposPorUsuario -- não há ON DELETE CASCADE entre
// as duas tabelas.
func (q *Queries) DeletarSetoresDosEscoposPorUsuario(ctx context.Context, usuarioID int64) error {
	_, err := q.db.Exec(ctx, deletarSetoresDosEscoposPorUsuario, usuarioID)
	return err
}

const obterEscopoSessaoPorUsuario = `-- name: ObterEscopoSessaoPorUsuario :many
SELECT
    ue.loja_id,
    ue.acesso_total_setores,
    array_remove(array_agg(ues.setor_id), NULL)::bigint[] AS setores_ids
FROM usuario_escopo ue
LEFT JOIN usuario_escopo_setor ues ON ues.escopo_id = ue.id
WHERE ue.usuario_id = $1
GROUP BY ue.id, ue.loja_id, ue.acesso_total_setores
ORDER BY ue.loja_id
`

type ObterEscopoSessaoPorUsuarioRow struct {
	LojaID             int64
	AcessoTotalSetores bool
	SetoresIds         []int64
}

// Formato que o front consome direto em EscopoAcessoGestor[] (login/sessão):
// um escopo por loja, com a lista de setor_id (vazia quando acesso_total_setores).
func (q *Queries) ObterEscopoSessaoPorUsuario(ctx context.Context, usuarioID int64) ([]ObterEscopoSessaoPorUsuarioRow, error) {
	rows, err := q.db.Query(ctx, obterEscopoSessaoPorUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObterEscopoSessaoPorUsuarioRow
	for rows.Next() {
		var i ObterEscopoSessaoPorUsuarioRow
		if err := rows.Scan(&i.LojaID, &i.AcessoTotalSetores, &i.SetoresIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterEscoposPorUsuario = `-- name: ObterEscoposPorUsuario :many
SELECT id, usuario_id, loja_id, acesso_total_setores, criado_em FROM usuario_escopo
WHERE usuario_id = $1
ORDER BY loja_id
`

func (q *Queries) ObterEscoposPorUsuario(ctx context.Context, usuarioID int64) ([]UsuarioEscopo, error) {
	rows, err := q.db.Query(ctx, obterEscoposPorUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsuarioEscopo
	for rows.Next() {
		var i UsuarioEscopo
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.LojaID,
			&i.AcessoTotalSetores,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterSetoresPorEscopos = `-- name: ObterSetoresPorEscopos :many
SELECT escopo_id, setor_id FROM usuario_escopo_setor
WHERE escopo_id = ANY($1::bigint[])
`

func (q *Queries) ObterSetoresPorEscopos(ctx context.Context, escopoIds []int64) ([]UsuarioEscopoSetor, error) {
	rows, err := q.db.Query(ctx, obterSetoresPorEscopos, escopoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsuarioEscopoSetor
	for rows.Next() {
		var i UsuarioEscopoSetor
		if err := rows.Scan(&i.EscopoID, &i.SetorID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
